### ISSUE TITLE
Deregistering components

### ISSUE THREAD

**Issue by grocid** [murlokswarm/app#100]
I noticed that that my applications memory goes incrementally up as I load components. Are the components kept in memory once loaded? Is there some way to free the memory if I know that I will use one component only at load?

**Comment by maxence-charriere** [comment]
Components are kept in memory the time they are mounted in a window. They are released each time the window is closed or they are replaced by another one.

Sent from my iPhone

On Jan 30, 2018, at 5:01 PM, Carl Löndahl <notifications@github.com<mailto:notifications@github.com>> wrote:


I noticed that that my applications memory goes incrementally up as I load components. Are the components kept in memory once loaded? Is there some way to free the memory if I know that I will use one component only at load?

**Comment by grocid** [comment]
So, to conditionally mount a different window, would this be the proper way?

´´´
// main
win.Mount(&a{})
func MountB()
    b := B{}
    win.Mount(&b{})
}

// Component A
type A struct{}

func (a *A) OnChange(value args.Value) {
     value == "hello" { 
        MountB()
    }
}

// Component B
type (b *B) struct{}

´´´

**Comment by grocid** [comment]
It seems that independent of the order I start with `A` and spawn `B` or vice versa, the memory used på the process is about 22 MBs and increase to around 60 when both are spawned (and the first one dereferenced). Maybe the registered component (like struct and code/const associated with the functions) remains in memory, but the instance does not?

This is a bit of a concern to me... I want my process to consume at most 50 MBs of RAM, but now it is about 100 MBs...

**Comment by maxence-charriere** [comment]
There is 3 process that are spawn:
- App
- App Web Content
- App Networking

the go layer is the first one.
For the size of the app, it is kind of difficult handle the size of the exec since it is garbage collected.
The Go runtime is the one who decides when it releases memory or not.

for 2 second one, those are controlled by webkit.

**Comment by maxence-charriere** [comment]
gonna close this for the moment.
Reopen if you think there really is a memory leak.
