### ISSUE TITLE
Windows Support Request

### ISSUE THREAD

**Issue by twisstosin** [murlokswarm/app#111]
It would be cool to have a windows version, what exactly is limiting?

**Comment by kingeasternsun** [comment]
dose the current version  support linux

**Comment by maxence-charriere** [comment]
It is currently only on mac and web.
Look like there is more interest for linux than windows ^^.

**Comment by mikeschinkel** [comment]
I would love to use GoLang instead of Electron+JS for a product we are building. But we have to run on Windows, so consider this a vote for Windows...

**Comment by mikeschinkel** [comment]
@maxence-charriere Thanks for asking.

Probably a UWP.  We don't know Windows well, we just know that are have a large base of potential users who will likely be using some form of Windows.

**Comment by Bmixo** [comment]
+1😜

**Comment by maxence-charriere** [comment]
Hello, thanks for the input 😄 !
I would love to implement all the drivers at the same time but I did not find yet a solution to this problem.
Meanwhile, I would love you to help me decide what should come next.
Please, let me know here: https://github.com/murlokswarm/app/issues/141

**Comment by 89apt89** [comment]
tbh win32 would probably be more beneficial but any windows driver is great 💯

**Comment by maxence-charriere** [comment]
I renamed #141 . Please, put your Windows related questions or suggestions there.
