### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by grocid** [murlokswarm/app#115]
I would like to see the possibility of drag and drop onto a window. Is that possible with the current driver?

**Comment by maxence-charriere** [comment]
I'm working on it. Here are some problem I have:
- Impossible to get an absolute file path form a web view.
- I can get the whole file. Works fine with reasonable file size. I tried to drop a movie and it made the
WKWebView crash.

**Comment by grocid** [comment]
Basically, the interesting part is to get the path to the file and not the actual data. The other part should be handled by the backend. I would like the component to have something like `OnDragAndDrop(name string)` which gets called.

**Comment by maxence-charriere** [comment]
Can see how it works here:
- https://github.com/murlokswarm/app/tree/master/examples/dragdrop
- https://github.com/murlokswarm/app/blob/master/examples/test/webview.go#L92

**Comment by grocid** [comment]
Cool, this is what I wanted to have. Thanks :-)
