### ISSUE TITLE
CSS not loading 

### ISSUE THREAD

**Issue by mcernik** [murlokswarm/app#118]
I'm having an issue getting the resources to load, in running your example apps, see screenshot of hello world one.  The app runs fine, just doesn't load the css, and thus not the images.  Any thoughts?  I included my a screenshot of my package setup as well..

![screen shot 2018-03-08 at 7 20 14 pm](https://user-images.githubusercontent.com/17438115/37185405-c4f3c632-2305-11e8-80b1-3fe79f532b31.png)

![screen shot 2018-03-08 at 7 18 45 pm](https://user-images.githubusercontent.com/17438115/37185367-95214f24-2305-11e8-8080-ed106d7a21e1.png)

**Comment by maxence-charriere** [comment]
where did you use go build ?
the resource directory have to be at the same level as the binary
```
./package
./package/myapp
./package/resources
```

**Comment by mcernik** [comment]
it was run from the src/hello directory from the above picture

**Comment by maxence-charriere** [comment]
Thats weird 😢 .

Did you type 
```hello``` or ```./hello``` to launch it ?

**Comment by mcernik** [comment]
Ahh, I just double clicked hello in Finder, ./hello from terminal worked.  Thx, just starting to learn go... :(

**Comment by maxence-charriere** [comment]
:)
