### ISSUE TITLE
Logo proporsal

### ISSUE THREAD

**Issue by LuigiBaute** [murlokswarm/app#130]
hello I would like to collaborate with your project for free, giving them a new logo or renewing the one they already have cheers!

**Comment by maxence-charriere** [comment]
Hello @LuigiBaute, thanks for offering your help.
I'm pretty satisfied with the current logo, but I'm open to new ideas that would better represent the project.
Feel free to contact me if you think about something or if you have some mocks.

**Comment by tjulises** [comment]
where can we get in touch? @maxence-charriere

**Comment by LuigiBaute** [comment]
where can we get in touch? @maxence-charriere

**Comment by LuigiBaute** [comment]
![logotipo app](https://user-images.githubusercontent.com/36426974/39903950-afda3a86-54a3-11e8-9590-729e74f6bd09.jpg)

Any ideas / suggestions are welcome, you could show me your current logo?
