### ISSUE TITLE
System Tray (Menu) support on Mac

### ISSUE THREAD

**Issue by hypnoglow** [murlokswarm/app#134]
Hi! 

As an example, I want to build an app that would just hang in tray showing an icon of a specific color based on app state. And when I click on that icon, a context menu appears with actions like "do this" and "do that". No real "windows" required for this app.

Is there a support for system tray in this package? Or do you plan any?

BTW Amazing package, thanks!

**Comment by maxence-charriere** [comment]
Hi,
Thanks for the kind words. 
It is currently not supported.
I ll put it on the todo list but i m pretty busy these times so i can t give you a release date.

**Comment by maxence-charriere** [comment]
I ll try to make it happen for the end of the month.

**Comment by maxence-charriere** [comment]
This is done!
Here is the example:
https://github.com/murlokswarm/app/tree/master/examples/statusmenu

**Comment by hypnoglow** [comment]
Wow, awesome! Thanks a lot @maxence-charriere , I'm going to try it soon when I find some spare time.

**Comment by maxence-charriere** [comment]
@hypnoglow let me know how it went or if you have some feedback about what to improve or how could we use this in a more simple way.
