### ISSUE TITLE
Cannot install goapp command

### ISSUE THREAD

**Issue by ravernkoh** [murlokswarm/app#136]
When doing `go get -u -v github.com/murlokswarm/app/...`, the installing of the `goapp` command fails with the following error

```
# github.com/murlokswarm/app/cmd/goapp
./exec.go:46:4: undefined: app.Error
```

**Comment by maxence-charriere** [comment]
Oh dammit i forgot to check the cmd in the last update, will fix this asap! Thanks for reporting this. So sorry for this.

**Comment by ravernkoh** [comment]
Thanks for being so responsive!
