### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by vicenteecl** [murlokswarm/app#138]
Greetings, Im the Co-Founder of ThinkPad, we are an independent graphic design company, actually we are in constantly upgrowth looking for new challenges, this one particularly call a lot my attention and i`ll will like to help you with, me and my professional partners would be more than pleased to collaborate with your project.

With nothing more to add, we`ll be waitng for your answer, have a nice day.

Vicent Castle.

**Comment by maxence-charriere** [comment]
Hello @vicenteecl 
Thanks for offering your help.
I don't really know how another logo could fit for this repo.

Best regards.
