### ISSUE TITLE
NSEventModifierFlagCommand   dependent on ？

### ISSUE THREAD

**Issue by daotianya** [murlokswarm/app#14]
./../../mac/menu.m:138:41: error: use of undeclared identifier 'NSEventModifierFlagCommand'

**Comment by maxence-charriere** [comment]
Hello daotianya, 
Thanks for the feedback.
are you running macOS sierra with the latest version of Xcode?

**Comment by daotianya** [comment]
y   Version 8.1 (8B62)

**Comment by maxence-charriere** [comment]
I think this is a problem related to your Xcode version.
Referring to the current doc: https://developer.apple.com/reference/appkit/nseventmodifierflags?language=objc

```NSEventModifierFlagCommand``` is the new standard. It replaces the ```NSCommandKeyMask``` which is deprecated.

here is my version of Xcode:
```Version 8.2.1 (8C1002)```

**Comment by maxence-charriere** [comment]
Hi, is this one still up ?
