### ISSUE TITLE
Next: Windows

### ISSUE THREAD

**Issue by maxence-charriere** [murlokswarm/app#141]
Hello, some stuff are happening here.
I'm writing changes that will bring better support for multi-platform dev.
Would like to know what is the next driver you would like to be implement.

[![](https://api.gh-polls.com/poll/01CFR6DZ5YQZNBQFDKKYJR1TDY/Android)](https://api.gh-polls.com/poll/01CFR6DZ5YQZNBQFDKKYJR1TDY/Android/vote)
[![](https://api.gh-polls.com/poll/01CFR6DZ5YQZNBQFDKKYJR1TDY/IOS)](https://api.gh-polls.com/poll/01CFR6DZ5YQZNBQFDKKYJR1TDY/IOS/vote)
[![](https://api.gh-polls.com/poll/01CFR6DZ5YQZNBQFDKKYJR1TDY/Linux)](https://api.gh-polls.com/poll/01CFR6DZ5YQZNBQFDKKYJR1TDY/Linux/vote)
[![](https://api.gh-polls.com/poll/01CFR6DZ5YQZNBQFDKKYJR1TDY/Windows)](https://api.gh-polls.com/poll/01CFR6DZ5YQZNBQFDKKYJR1TDY/Windows/vote)

**Comment by Arie-vw** [comment]
> Windows is what is coming next. I ll use this issue to give news on the development.
> Feel free to post your suggestions or any questions related to windows here.

Great!!!

**Comment by maxence-charriere** [comment]
Step by step, little by little...

![capture2](https://user-images.githubusercontent.com/2692731/46127437-82be9600-c1e5-11e8-9291-b3606a42eff9.PNG)

Now launching the go program with the uwp using desktop bridge.

The hack works that way:
- [Built an UWP](https://github.com/murlokswarm/uwp) with visual studio 2017 in Release mode for x64 with .net native.
- UWP .dll, .exe and .pri are copied in the goapp directory.
- When building with `goapp win build`:
  - create the package.
  - go build.
  - copy the UWP .dll, .exe and .pri into the package.
  - generate the AppxManifest.xml.
  - deploying on local machine.
- launch the app with start menu.

I still have a problem:
When generating AppxManifest.xml, if I put a different value for the identity name, the uwp program crash at launch.

This is working:
```xml
<Identity Name="4a99c091-2185-434d-8088-4b6c643f38fc" Publisher="CN=Maxence" Version="1.0.0.0" />
```

This is not working:
```xml
<Identity Name="goapp" Publisher="CN=Maxence" Version="1.0.0.0" />
```

I tried to put a different guid but it does not work either.

If someone have an idea, please let me know!

**Comment by txthinking** [comment]
Is there a planned release time? 👍

**Comment by maxence-charriere** [comment]
Got a good improvements since last posted update. I don't want to give a release time. Just I expect to have it by the end of the year.

**Comment by zet4** [comment]
This looks awesome, is there anything others can contribute to this to get it rolling sooner? Really itching to play with it.

**Comment by maxence-charriere** [comment]
@zet4 Thank for proposing. Right now I'm still in a spot where I'm defining how the communication go/winrt works.
Once it done I could post an update here with some stuff to implements for the ones who would be up to the task.

**Comment by Wulfheart** [comment]
I'm so excited. When do you expect it to be rolled out?

**Comment by maxence-charriere** [comment]
@Wulfheart when it will be ready :)

**Comment by Wulfheart** [comment]
I'm waiting for it. This concept looks promising and the learning curve quite flat.

Am 30. Oktober 2018 17:01:37 MEZ schrieb Maxence Charriere <notifications@github.com>:

**Comment by maxence-charriere** [comment]
Hello folks, just wanted to give a little update on how it's going.

Progress since last:
* Go to C# communication.
* C# to Go communication.
* Can display hello world example!

What next:
* CSS files
* Js to Go communication

Here is a screenshot of the hello world example for now:

![capture3](https://user-images.githubusercontent.com/2692731/48475350-743a3700-e7b1-11e8-852a-8666321809f2.PNG)

**Comment by maxence-charriere** [comment]
Folks, I warn you, the code is pretty dirty right now but...

![capture4](https://user-images.githubusercontent.com/2692731/48541990-d9099600-e872-11e8-9e0c-000064a46749.PNG)

On this note, I going to sleep now.

**Comment by Wulfheart** [comment]
Even if the code is really dirty: Can we use it right now?

**Comment by maxence-charriere** [comment]
@Wulfheart Unfortunately it need a lot of polish. I will do a release when it will be usable. I don't want to drop something that hacky and scare the people who want to try it. But the prototype is here and now I can build on the top until it become enough good.

Omg, I spent months to get there 😭 .

**Comment by atlasdatatech** [comment]
Very looking forward to

**Comment by maxence-charriere** [comment]
Working hard on it, the goapp tool is in a spot where i m satisfied. If you want to try it you can go to the 4.0.0 branch.

You will need a windows machine. Mingw64 and the windows 10 sdk to make it work.

You also will need to install the goapp cmd tool from this branch.

Very experimental and a lot of stuff is missing. The hello world example is working. Did not test the others since its far to be feature complete.

**Comment by maxence-charriere** [comment]
Just some little news about this:
- Working on a new example that allow to enumerate and test what the package can do. It helps a lot with the Windows implementations.
- App can be opened from file or url.
- Working on window related feature now.
- Just implemented frosted background.
- Starting the UWP messy window handling...

And here is what it looks like:

![capture5](https://user-images.githubusercontent.com/2692731/49956900-3ec16000-febb-11e8-9a34-2982092c5289.PNG)

**Comment by zet4** [comment]
Looks awesome, though I feel like Apple fanboys might complain about windows looking apps on their platform haha

**Comment by zet4** [comment]
I am curious though, what's the performance like, compared to say, Electron.

**Comment by maxence-charriere** [comment]
In term of the graphic performances it is like comparing Edge vs Chrome. 

This is more smooth, use less battery and is less heavy. Electron rendering supports better standards and is more stable.
Sometime later it would not matter anymore since Microsoft will provide Chrome based webview. When it happen this package will have an option to chose which rendering engine to use, and will default to the Chrome based one for better cross platform compatibility.

No need to compare the javascript part since the javascript layer is just a bridge between the webview and Go. All other computations are Go native code which gonna be faster and more memory efficient than Electron 's javascript.

All of this is theory and to be honest, I did not benchmark the cost of passing data from go to UWP|Cocoa.
I let raw graphic performances to the expert in this domain (Google, Apple, Microsoft). This package is about giving a good and easy to use API to build app with Go.

**Comment by enggjiten** [comment]
can you share build steps for windows
I tried with below commands
 .\goapp.exe win init

Getting error with below commands
 .\goapp.exe win build
 .\goapp.exe win run -dev

x fork/exec C:\Users\user\AppData\Local\Temp\goapp\app\app.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

Am i missing something

**Comment by maxence-charriere** [comment]
@enggjiten are you on 32 or 64 bit Windows ?

**Comment by enggjiten** [comment]
I have 64-bit Windows 10 Pro.
Go version:
go version go1.11.2 windows/amd64
MingW64 \x86_64-8.1.0-win32-seh-rt_v6-rev0

**Comment by maxence-charriere** [comment]
No just trying to see the differences.

A couple of thing:
- Can you run `goapp win run -h` and copy/paste the output.
- Can you `go build` your program after commenting the part that uses `app.Run`, add a `fmt.Println("whatever")` and try to launch the generated program to see if the error is there too.

**Comment by enggjiten** [comment]
Correct me if i am doing something wrong here.
I built the latest goapp.exe with 4.0.0 repo.
Go to \app\examples\demo
Run src\github.com\murlokswarm\app\examples\demo> ..\..\cmd\goapp\goapp.exe win
build -v

Output::
 creating demo.app
‣ building executable
    github.com/murlokswarm/app/drivers/win
    # github.com/murlokswarm/app/drivers/win
    ..\..\drivers\win\driver.go:259:3: unknown field 'TitlebarHidden' in struct literal of type app.WindowConfig
    ..\..\drivers\win\window.go:59:3: cannot use c.OnMove (type func(app.Window)) as type func(float64, float64) in field value
    ..\..\drivers\win\window.go:60:3: cannot use c.OnResize (type func(app.Window)) as type func(float64, float64) in field value
    ..\..\drivers\win\window.go:61:3: cannot use c.OnFocus (type func(app.Window)) as type func() in field value
    ..\..\drivers\win\window.go:62:3: cannot use c.OnBlur (type func(app.Window)) as type func() in field value
    ..\..\drivers\win\window.go:63:3: cannot use c.OnFullScreen (type func(app.Window)) as type func() in field value
    ..\..\drivers\win\window.go:64:3: cannot use c.OnExitFullScreen (type func(app.Window)) as type func() in field value
    ..\..\drivers\win\window.go:65:3: cannot use c.OnMinimize (type func(app.Window)) as type func() in field value
    ..\..\drivers\win\window.go:66:3: cannot use c.OnDeminimize (type func(app.Window)) as type func() in field value
    ..\..\drivers\win\window.go:67:3: cannot use c.OnClose (type func(app.Window) bool) as type func() bool in field value
    ..\..\drivers\win\window.go:67:3: too many errors
x exit status 2

**Comment by maxence-charriere** [comment]
oh, yes this is normal! the last 4.0.0 merge come from Mac modifications, it should work on [window-on-Windows](https://github.com/murlokswarm/app/tree/window-on-Windows).

**Comment by maxence-charriere** [comment]
Just warn you if you arrive to launch it, support is super limited now, still a lot of work to do in order to make it usable to build something.

Also, `goapp win run` without `-dev` option is making the app crash.

Let me know how it goes.

**Comment by maxence-charriere** [comment]
Can you do a dir in demo.app and copy paste the output ?

Sent from my iPhone

On Dec 14, 2018, at 3:26 AM, enggjiten <notifications@github.com<mailto:notifications@github.com>> wrote:


UWP App built and installed.
When i try open it try to do something but could not open up.

**Comment by enggjiten** [comment]
i tried again with branch 4.0.0

Run below command and got result as below.
\src\github.com\murlokswarm\app\examples\demo> ..\..\cmd\goapp\goapp.exe win
run -dev
start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ start goapp-demo://
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

x exit status 1

Instead of UWP app, can we run executable container ?

**Comment by maxence-charriere** [comment]
what do you mean by executable container ?
Is the app is at least installed ? when you go on the start menu and type demo.

**Comment by enggjiten** [comment]
Yes, it is build and installed but not running.
I got eventviewer logs
```
Unable to start a DCOM Server: jiten_1.0.0.0_neutral__xgkf2qwfy5v6a!jiten as Unavailable/Unavailable. The error:
"2"
Happened while starting this command:
"C:\Users\jiten\Documents\golaunch\src\github.com\murlokswarm\app\examples\demo\demo.app\uwp.exe" -ServerName:jiten.AppXqanewx1bwvrv122c6t62bx49f5nwzagk.mca
```

Let me know if you know the solution of this.

**Comment by maxence-charriere** [comment]
Just a heads up here. The windows driver is too hacky and unstable.  I experienced a lot with it and I don't think its good to go in a release.

During the past week I though about what is the future for this package. I posted another issue that deals with that question:
https://github.com/murlokswarm/app/issues/262
