### ISSUE TITLE
Example crashing right away after go build or go run

### ISSUE THREAD

**Issue by euforic** [murlokswarm/app#15]
I tried to just  go build the example project then execute the binary, but it crashes right after it starts. The weird thing is if I use `macpack` to build it then it doesn't crash. I'm guessing the app wrapper provides data where the raw build does not.

## Go ENV

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/euforic/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.5/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.5/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3x/0rnfwj_x1jz2p0gzh_gg7_600000gn/T/go-build912724629=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

## Crash Output

```
INFO  2017/01/30 14:00:47 driver.go:31: driver *mac.Driver is loaded
INFO  2017/01/30 14:00:47 component.go:62: main.Hello has been registered under the tag Hello
INFO  2017/01/30 14:00:47 component.go:62: main.AppMainMenu has been registered under the tag AppMainMenu
INFO  2017/01/30 14:00:47 component.go:62: main.WindowMenu has been registered under the tag WindowMenu
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fffb3c24b52]

runtime stack:
runtime.throw(0x41a1554, 0x2a)
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4141160, 0xc42004df20, 0x0)
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/cgocall.go:131 +0x110 fp=0xc42004def0 sp=0xc42004deb0
github.com/murlokswarm/mac._Cfunc_Driver_Run()
	??:0 +0x41 fp=0xc42004df20 sp=0xc42004def0
github.com/murlokswarm/mac.(*Driver).Run(0xc420010280)
	/Users/euforic/go/src/github.com/murlokswarm/mac/driver.go:56 +0x14 fp=0xc42004df28 sp=0xc42004df20
github.com/murlokswarm/app.Run()
	/Users/euforic/go/src/github.com/murlokswarm/app/app.go:43 +0x35 fp=0xc42004df40 sp=0xc42004df28
main.main()
	/Users/euforic/go/src/github.com/blevein/play/examples/mac/hello/main.go:31 +0x30 fp=0xc42004df48 sp=0xc42004df40
runtime.main()
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/proc.go:183 +0x1f4 fp=0xc42004dfa0 sp=0xc42004df48
runtime.goexit()
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42004dfa8 sp=0xc42004dfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [chan receive]:
github.com/murlokswarm/app.startUIScheduler()
	/Users/euforic/go/src/github.com/murlokswarm/app/ui.go:11 +0x51
created by github.com/murlokswarm/app.init.1
	/Users/euforic/go/src/github.com/murlokswarm/app/ui.go:17 +0x35
```

**Comment by maxence-charriere** [comment]
Hi Euforic,
Thank you very much for try this and go with macpack too.

I'm gonna check this assap.
Just to have more hints,
What version of macOS do you use?
Can you try to launch it again, (I remember this thing happened to me once but i was not able to reproduce it). I may have an idea though.

**Comment by euforic** [comment]
<img width="233" alt="screen shot 2017-01-30 at 2 17 44 pm" src="https://cloud.githubusercontent.com/assets/395386/22444232/ec7aac1c-e6f6-11e6-9ba3-ab9d301aed4d.png">

**Comment by maxence-charriere** [comment]
Thank you.

**Comment by maxence-charriere** [comment]
Hey @euforic,
After some search I found this article: https://github.com/golang/go/wiki/LockOSThread.
I modified the app package to use this.
Could you try if you still have the issue?
Thanks.

**Comment by euforic** [comment]
No luck 

```
INFO  2017/01/31 13:13:04 driver.go:31: driver *mac.Driver is loaded
INFO  2017/01/31 13:13:04 component.go:62: main.Hello has been registered under the tag Hello
INFO  2017/01/31 13:13:04 component.go:62: main.AppMainMenu has been registered under the tag AppMainMenu
INFO  2017/01/31 13:13:04 component.go:62: main.WindowMenu has been registered under the tag WindowMenu
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fffc223cb52]

runtime stack:
runtime.throw(0x41a14f4, 0x2a)
        /usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
        /usr/local/Cellar/go/1.7.5/libexec/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4141100, 0xc420051f20, 0x0)
        /usr/local/Cellar/go/1.7.5/libexec/src/runtime/cgocall.go:131 +0x110 fp=0xc420051ef0 sp=0xc420051eb0
github.com/murlokswarm/mac._Cfunc_Driver_Run()
        ??:0 +0x41 fp=0xc420051f20 sp=0xc420051ef0
github.com/murlokswarm/mac.(*Driver).Run(0xc42007c140)
        /Users/euforic/go/src/github.com/murlokswarm/mac/driver.go:56 +0x14 fp=0xc420051f28 sp=0xc420051f20
github.com/murlokswarm/app.Run()
        /Users/euforic/go/src/github.com/murlokswarm/app/app.go:49 +0x35 fp=0xc420051f40 sp=0xc420051f28
main.main()
        /Users/euforic/go/src/github.com/blevein/play/main.go:31 +0x30 fp=0xc420051f48 sp=0xc420051f40
runtime.main()
        /usr/local/Cellar/go/1.7.5/libexec/src/runtime/proc.go:183 +0x1f4 fp=0xc420051fa0 sp=0xc420051f48
runtime.goexit()
        /usr/local/Cellar/go/1.7.5/libexec/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420051fa8 sp=0xc420051fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/Cellar/go/1.7.5/libexec/src/runtime/asm_amd64.s:2086 +0x1

goroutine 19 [chan receive]:
github.com/murlokswarm/app.startUIScheduler()
        /Users/euforic/go/src/github.com/murlokswarm/app/ui.go:11 +0x51
created by github.com/murlokswarm/app.init.2
        /Users/euforic/go/src/github.com/murlokswarm/app/ui.go:17 +0x35
```

**Comment by euforic** [comment]
It might be because UI function are called outside the package and do not use the same locked thread.

**Comment by maxence-charriere** [comment]
Mmmm, I gonna recheck all the cocoa call tonight when i get home.
Thank you very much for the feedback.

**Comment by maxence-charriere** [comment]
I also moved the launch of the UIScheduler in the Run function to ensure it is not created before the channel.
Can you update and try it please ?

**Comment by euforic** [comment]
I updated all the packages. Still no luck. I will try to debug and see if I can find anymore out. Thanks again for the help.

**Comment by dmonay** [comment]
@maxence-charriere I'm having the same issue with a nearly identical stack trace:
```
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [chan receive]:
github.com/murlokswarm/app.startUIScheduler()
	/Users/Dima/workspace/go/src/github.com/murlokswarm/app/ui.go:11 +0x51
created by github.com/murlokswarm/app.Run
	/Users/Dima/workspace/go/src/github.com/murlokswarm/app/app.go:49 +0x35

**Comment by maxence-charriere** [comment]
@dmonay Thanks for the feedback, I will try to find more on the issue tonight.

**Comment by maxence-charriere** [comment]
@dmonay @euforic 
I did a refactor on https://github.com/murlokswarm/mac
to ensure that Cocoa init functions are called after runtime.LockOSThread().

Could you ```go get -u github.com/murlokswarm/mac``` and see if you still have the issue?

Thank you very much again for taking time for this.

**Comment by dmonay** [comment]
I am still getting the same error:
```
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [chan receive]:
github.com/murlokswarm/app.startUIScheduler()
	/Users/Dima/workspace/go/src/github.com/murlokswarm/app/ui.go:11 +0x51
created by github.com/murlokswarm/app.Run
	/Users/Dima/workspace/go/src/github.com/murlokswarm/app/app.go:43 +0x35
```

**Comment by maxence-charriere** [comment]
@dmonay, is it the full message ?

**Comment by dmonay** [comment]
It's the part that I think is most relevant. The full message is:
```
INFO  2017/01/31 23:29:32 driver.go:31: driver *mac.Driver is loaded
INFO  2017/01/31 23:29:32 component.go:62: main.Hello has been registered under the tag Hello
INFO  2017/01/31 23:29:32 component.go:62: main.AppMainMenu has been registered under the tag AppMainMenu
INFO  2017/01/31 23:29:32 component.go:62: main.WindowMenu has been registered under the tag WindowMenu
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7fffd4ce71a4]

runtime stack:
runtime.throw(0x41a15df, 0x2a)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4141200, 0xc420051f18, 0xc400000000)
	/usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc420051ee8 sp=0xc420051ea8
github.com/murlokswarm/mac._Cfunc_Driver_Run()
	??:0 +0x41 fp=0xc420051f18 sp=0xc420051ee8
github.com/murlokswarm/mac.(*Driver).Run(0xc420016380)
	/Users/Dima/workspace/go/src/github.com/murlokswarm/mac/driver.go:59 +0x14 fp=0xc420051f20 sp=0xc420051f18
github.com/murlokswarm/app.Run()
	/Users/Dima/workspace/go/src/github.com/murlokswarm/app/app.go:44 +0x4d fp=0xc420051f40 sp=0xc420051f20
main.main()
	/Users/Dima/workspace/go/src/github.com/dmonay/mac-app/main.go:31 +0x30 fp=0xc420051f48 sp=0xc420051f40
runtime.main()
	/usr/local/go/src/runtime/proc.go:183 +0x1f4 fp=0xc420051fa0 sp=0xc420051f48
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420051fa8 sp=0xc420051fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [chan receive]:
github.com/murlokswarm/app.startUIScheduler()
	/Users/Dima/workspace/go/src/github.com/murlokswarm/app/ui.go:11 +0x51
created by github.com/murlokswarm/app.Run
	/Users/Dima/workspace/go/src/github.com/murlokswarm/app/app.go:43 +0x35

**Comment by maxence-charriere** [comment]
can you put your playground on git hub ?

**Comment by dmonay** [comment]
I just `git clone`d the example repo and ran
```
$ go build
$ ./hello
```

**Comment by maxence-charriere** [comment]
yeah i figured out ^^, that why i removed the comment ;) sorry

**Comment by dmonay** [comment]
No problem. I'll look into it as well. I'm curious now. Are you unable to replicate this issue?

**Comment by maxence-charriere** [comment]
no, I also had friend who tried it on his mac this morning and everything went fine in the first try.

**Comment by dmonay** [comment]
What go version are you using? I'm on `1.7.3`

**Comment by maxence-charriere** [comment]
▶ go version
go version go1.7.5 darwin/amd64

but the example worked before my last go update (was last week)

**Comment by maxence-charriere** [comment]
do it works if you macpack it ?

**Comment by maxence-charriere** [comment]
https://github.com/murlokswarm/macpack

**Comment by euforic** [comment]
In think when it runs via macpack it runs on the main thread by default (just a guess though)

**Comment by dmonay** [comment]
Yes, that works! But now I have no access to logging if I want to do development.

**Comment by maxence-charriere** [comment]
what if you do ```./[yourapp].app/Contents/MacOS/[yourapp]```?

**Comment by dmonay** [comment]
That crashes in the same manner as before.

**Comment by maxence-charriere** [comment]
Do you often use Xcode? If no try to launch it and see if it ask you to accept term and conditions.
That would be weird if it's that... but let see.

**Comment by maxence-charriere** [comment]
In this case, the only thing that macpack is doing is creating the .app folder and putting resources and executable in the good place.

**Comment by dmonay** [comment]
I did not have to accept terms and conditions, but Xcode did install some new components. However the app is still crashing if I run the Go binary.

**Comment by maxence-charriere** [comment]
did you rebuild after accepting term and condition + new installs ?

**Comment by dmonay** [comment]
Yes

**Comment by dmonay** [comment]
I did not accept terms and conditions though, just new components.

**Comment by maxence-charriere** [comment]
oh, can you accept it ?

**Comment by dmonay** [comment]
Updated my comment to clarify that Xcode did not prompt me to accept new terms and conditions. It just prompted to install new components.

**Comment by maxence-charriere** [comment]
dammit :(

@dmonay 
I did another refactor on the cocoa part where it crash.
I don't think it should change the thing but there could be a chance.
Can you update the mac package and try again please?

**Comment by euforic** [comment]
@maxence-charriere might be worth a look to checkout https://github.com/andlabs/ui/blob/master/link_darwin_amd64.go#L18-L23 see how they solve it

**Comment by maxence-charriere** [comment]
Hey @euforic thank you for the link, I just wrote something similar. I would like to have a feedback on the current change before trying this one though.

**Comment by dmonay** [comment]
Still crashing :(

**Comment by mcastilho** [comment]
I am getting the same error on mine.... ;-(

**Comment by joeblew99** [comment]
is working for me. really awesome project.



In case this helps i am on:
Xcode
Version 8.2.1 (8C1002)

**Comment by maxence-charriere** [comment]
Dammit, have to find why this thing fails on your machines!

**Comment by joeblew99** [comment]
maybe ask everyone to submit their environments.
Data being:
- go version
- go env
- some OSX one i dont know ?

maybe something will stick out.

**Comment by joeblew99** [comment]
I can go build and it works.

````
x-MacBook-Pro:hello apple$ go version
go version go1.7.4 darwin/amd64
x-MacBook-Pro:hello apple$ go env
GOARCH="amd64"
GOBIN="/Users/apple/workspace/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build880197388=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"


```

**Comment by maxence-charriere** [comment]
👍 . Could you give these:
- MacOS version
- Xcode version
- Have you accepted Xcode licence/terms/conditions?
- ```go env```

**Comment by maxence-charriere** [comment]
- Status: OK
- MacOS Mac:<img width="565" alt="screen shot 2017-02-01 at 11 49 40" src="https://cloud.githubusercontent.com/assets/2692731/22523514/8cf7a798-e874-11e6-8df6-bf648a3d9eb9.png">
- Xcode: Version 8.2.1 (8C1002)
- Yes
- Go: 
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/maxence/Dev/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.5/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.5/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/07/tj_2fpcd5lv00gj1shc_kgqw0000gn/T/go-build395864183=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by euforic** [comment]
@maxence-charriere  I made a quick cli command to output helpful info for debugging to the system clipboard this way people can just ctrl+v into the issues body

```
echo "\n\`\`\`\n[OS]\n$(sw_vers)\n\n[XCODE]\n$(xcodebuild -version)\n\n[GO]\n$(go env)\n\`\`\`" | pbcopy
```

**Example Output**

```
[OS]
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32

[XCODE]
Xcode 8.2.1
Build version 8C1002

[GO]
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/euforic/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.5/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.5/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3x/0rnfwj_x1jz2p0gzh_gg7_600000gn/T/go-build337349901=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by maxence-charriere** [comment]
nice, awesome @euforic . Thank you very much.

**Comment by joeblew99** [comment]
```

[OS]
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32

[XCODE]
Xcode 8.2.1
Build version 8C1002

[GO]
GOARCH="amd64"
GOBIN="/Users/apple/workspace/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build123661264=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"\n

```

**Comment by AbeEstrada** [comment]
```
[OS]
ProductName:   Mac OS X
ProductVersion: 10.12.3
BuildVersion:   16D32

[XCODE]
Xcode 8.2.1
Build version 8C1002

[GO]
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Abe/Code/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.5/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.5/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w3/6yfj1hz96093jfryxvytvsmc0000gn/T/go-build819544189=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by maxence-charriere** [comment]
can you precise if it working or not please

**Comment by AbeEstrada** [comment]
I have the same `goroutine 17 [syscall, locked to thread]:` crash

**Comment by dmonay** [comment]
Status: KO

```
[OS]
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67

[XCODE]
Xcode 8.2.1
Build version 8C1002

[GO]
GOARCH="amd64"
GOBIN="/Users/Dima/workspace/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Dima/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sy/kwhbgrgs4x991_6xw7lm5vxc0000gn/T/go-build677151442=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"```

**Comment by maxence-charriere** [comment]
Hey guys, could you try with this branch of mac package:
https://github.com/murlokswarm/mac/pull/11

I modified the way the app launches but you will need to ```macpack build``` and then launch it this way: ```./hello.app/Contents/MacOS/hello```

let me know if it still crashes

**Comment by dmonay** [comment]
I am still getting the crash.

**Comment by maxence-charriere** [comment]
@dmonay, can you create a macOS app with Xcode in Objective C and see if it crashes too ?

**Comment by dmonay** [comment]
I can do that later today. However, as I noted yesterday, the app does work when opened by double clicking the icon that `macpack` generates. It only fails when I try to execute the binary from the terminal.

**Comment by maxence-charriere** [comment]
yeah, but that's weird, and this way you are not able to get app log. I really wonder what this issue could be, look like we have the same setup.

**Comment by maxence-charriere** [comment]
does the app crash if you comment L20 ```win = newMainWindow()``` ?
(you should just have the menu bar with that)

**Comment by dmonay** [comment]
Still crashes.

**Comment by maxence-charriere** [comment]
Mmm, i m gonna try some installs on random mac, hope i ll be able to recreate the problem.

**Comment by dmonay** [comment]
@maxence-charriere any luck?

**Comment by maxence-charriere** [comment]
@dmonay, I was sick today and I was not able to get the machines I wanted to try. Have to delay this one a little bit :(.

**Comment by maxence-charriere** [comment]
@dmonay do you also have the new macbook pro ?

**Comment by joeblew99** [comment]
@maxence-charriere  you can also use travis to test on lots of differnt macs.

https://docs.travis-ci.com/user/osx-ci-environment/

https://www.macstadium.com/blog/how-travis-ci-halved-boot-times-for-os-x-and-ios-testing-at-macstadium/

**Comment by maxence-charriere** [comment]
=> For the ones who use macpack:
 @joeblew99 made me realized that the repo was not up to date.

Before use the new version, you should **delete** ```mac.json```.
Also the command to launch the build is ```macpack build```

**Comment by maxence-charriere** [comment]
Hey guys, I tried to install it on some fresh MacBooks and it worked.
@euforic have the latest macbook,
What about you @AbeEstrada @dmonay @mcastilho ?

There was a little update related to WebKit include.
Can you ``` go get -u github.com/murlokswarm/mac``` and retry.

The last thing but would be totally dumb is just restart the computer.
I' sorry guys, I'm really unable to reproduce this :(.

**Comment by AbeEstrada** [comment]
@maxence-charriere same crash message: `goroutine 17 [syscall, locked to thread]:`

I also have the 2016 MBP with TouchBar

**Comment by mcastilho** [comment]
I have the 2016 MBP with TouchBar also

**Comment by maxence-charriere** [comment]
look like we have something here.
I start to suspect some initializations related with the touchbar that requires the app to be packaged.
What about you @dmonay ?

**Comment by dmonay** [comment]
@maxence-charriere I do not have the touchbar - I'm on a Late 2013 MacBook Pro 15". I just upgraded to 10.12.3 from 10.12.2 so will test shortly to make sure it wasn't a weird version bug.

**Comment by dmonay** [comment]
@maxence-charriere still seeing the same problem. The app works as expected when built by macpack, but fails when built with `go build`. I am also now seeing this warning after running `macpack build`:
```
Warning:
  Sandbox mode requires sign-id flag to be set.
  Valid ids can be seen with: security find-identity -v -p codesigning
  See the 'Obtaining Your Signing Identities' section from
  https://developer.apple.com/library/content/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html
  for creating one.
```

**Comment by maxence-charriere** [comment]
the warning is normal.
App in sandbox requires to be signed. You can get rid od the message by setting sandbox to false into mac.json.

I have really no idea of the why it crashes :(.

**Comment by dmonay** [comment]
Ok, I'll use `macpack build` for now. Thanks for trying to figure it out 👍

**Comment by maxence-charriere** [comment]
@dmonay @mcastilho @euforic 
Hey guys, I got some problems with the last Xcode and go updates.
Crash when the app start.

Was able to fix that by building with this command:
```
go build -ldflags -s
```

Could you try id it work?

**Comment by zhaoyibo** [comment]
@maxence-charriere Thank you! It works for me.

```
[OS]
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195

[XCODE]
Xcode 8.3.1
Build version 8E1000a

[GO]
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yibo/golang/work"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1b/fpz1fkh15zs0wtx7h8r6d7500000gn/T/go-build237889986=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by maxence-charriere** [comment]
@zhaoyibo Awesome !
Gonna keep this one open to have more feedbacks though.

**Comment by smoya** [comment]
Same here. This https://github.com/murlokswarm/app/issues/15#issuecomment-291596635 "fixed" the problem, which in my case was having just a killing signal.
