### ISSUE TITLE
What the advantages of this concept over Electron?

### ISSUE THREAD

**Issue by lenaten** [murlokswarm/app#16]

**Comment by maxence-charriere** [comment]
The interesting thing is the use of Golang and all its awesome features available right out of the box: 
- Code formatting 
- Unit testing (with code coverage) 
- Benchmarks 
- Memory profile
- High performances
- Concurrency model
- Go community

Also, there is no special API to handle custom stuff like menu.
You write it exactly like you would write any component.
Take a look here:
- Menu:  https://github.com/murlokswarm/examples/blob/master/mac/hello/menu.go
- View: https://github.com/murlokswarm/examples/blob/master/mac/hello/hello.go

Even if it is available only on MacOS today, this is designed to be portable, even on Android and IOS.

Please, note this is a very young project and it had to start somewhere.

**Comment by tj** [comment]
👍 I just wanted to say, this is awesome. Getting to use the Go stdlib in desktop apps, let alone all the awesome third-party packages is really powerful. Nice work! If I ever make something with this that makes money you'll definitely see some of it haha

**Comment by maxence-charriere** [comment]
Thank for the kind words :)
