### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by mmlkrx** [murlokswarm/app#17]
It would be great to include more links to tutorials/blog posts from people using murlok app to create desktop applications. Do you know of any more resources like that?

**Comment by maxence-charriere** [comment]
Hey @mmlkrx 
Unfortunately there is not a lot, I just started communication about the package last Monday.
This is very young.

The 2 only examples available currently are:
- https://github.com/murlokswarm/examples/tree/master/mac/hello
- https://github.com/maxence-charriere/jubiz

If there is an example of a particular feature you would like to see, let me know, I ll try to produce it between fixing current issues and developing the Windows driver.

**Comment by mmlkrx** [comment]
Great, thanks for the quick reply!

**Comment by maxence-charriere** [comment]
Just an update on this one,
I'm writing some example showing how to do simple tasks with the library.
You can find it in the ```examples``` folder.
