### ISSUE TITLE
Anyway to package mac binaries?

### ISSUE THREAD

**Issue by malkomalko** [murlokswarm/app#175]
First of all, I have been playing around with this project on the side for a while, but I was wondering if there was anyway to package up the app build into a runnable application.

I saw your macpack package, but it looks like it's fallen a little out of date.

Cheers!

**Comment by maxence-charriere** [comment]
Hello.
Yes there is:
Get the latest version 
```sh
go get -u -v github.com/murlokswarm/app/...
```

It should install https://github.com/murlokswarm/app/tree/master/cmd/goapp.

The you can go where your program is and use
```sh
# Build a .app:
goapp mac build -bundle

# Help:
goapp Mac build -h
```

If you want to customize the package, refer to:
- https://github.com/murlokswarm/app/blob/master/drivers/mac/driver.go#L46
- https://github.com/murlokswarm/app/blob/master/drivers/mac/bundle.go

**Comment by malkomalko** [comment]
Outstanding!

**Comment by maxence-charriere** [comment]
Ok it's an issue with the plist and the go build, gonna fix it. Thanks for report this.
as a temporary fix, don't use the 'Bundle.Name' field.

**Comment by maxence-charriere** [comment]
This is fixed.

```sh
# Update:
go get -u -v github.com/murlokswarm/app/...
```

Please let me know if there is still a problem or if you find another issue.
Thanks for the feedback.

**Comment by malkomalko** [comment]
Works great.  Thanks for the fix!
