### ISSUE TITLE
Are there any possible ways to package the app to a normal macOS application ?  

### ISSUE THREAD

**Issue by bitflying** [murlokswarm/app#179]
Hi, friends,

Are there any possible ways to package the app to a normal macOS application ?  

Thanks in advance!

**Comment by maxence-charriere** [comment]
Yes, take a look on the issue bellow :)
https://github.com/murlokswarm/app/issues/175

**Comment by maxence-charriere** [comment]
Duplicate of #175

**Comment by maxence-charriere** [comment]
Also created a wiki page that contains the answer of the duplicate.
https://github.com/murlokswarm/app/wiki/Package-MacOS-app

Please reopen the issue and add suggestions if you think this is too light.
Best.

**Comment by bitflying** [comment]
Thanks, Maxence Charriere,

It is great!
