### ISSUE TITLE
Extra template function inject support

### ISSUE THREAD

**Issue by lunny** [murlokswarm/app#19]
As title.

**Comment by maxence-charriere** [comment]
I m not sure to understand what the title mean. Ca you give an example or use case you have in mind?

**Comment by lunny** [comment]
see https://godoc.org/text/template#Template.Funcs , I mean how to set the customized functions to template string.

**Comment by maxence-charriere** [comment]
ohhh, interesting, for the moment this is not possible.
👍 

 I will take a look about how to allow that. Agree that could be a good way to extend the markup possibilities.

**Comment by joeblew99** [comment]
I am using this:
https://github.com/mh-cbon/template-compiler

- 5 to 10 times faster, because templates are compiled.
- works with standard go en.
- supports huge library of funcmaps too.  https://github.com/mh-cbon/template-compiler#working-with-funcmap 
- more to come it looks like.
