### ISSUE TITLE
With multiple components, when a button in one component is clicked, how to let another component to re-render?

### ISSUE THREAD

**Issue by bitflying** [murlokswarm/app#195]
With multiple components, when a button in one component is clicked, how to let another component to re-render?

**Comment by bitflying** [comment]
Hi, friends,
In a component, when we change some data, we just use app.render(thiscomponent) to re-render itself. but sometime, we also want to re-render another components (parent component or brother component). 

So, 
1. Is there any simple method to get another component's compo to use app.render() to do so.
2. Can we pass a callback function from parent component to the component, we can call it, later in the component to re-render.

Thanks in advance!

**Comment by maxence-charriere** [comment]
you also have a full example of this here: https://github.com/murlokswarm/app/tree/master/examples/action-event.

Let me know if it solve your problem.

**Comment by maxence-charriere** [comment]
Closing this, please reopen if it did not solved your problem.

**Comment by bitflying** [comment]
Thank you, it works!
