### ISSUE TITLE
RPC like object to do javascript calls

### ISSUE THREAD

**Issue by lunny** [murlokswarm/app#21]

**Comment by maxence-charriere** [comment]
drop a .js file in ```resources/js```
It will be auto included.
then call your js function into a ```<script></script>```

I think you can also declare and call a func from a script tag.

Note that I never tested that.

**Comment by maxence-charriere** [comment]
I'm sorry @lunny 
I did some try and look like the current implementation make javascript more difficult than what I expected.

Ultimately this is not bad because the long term plan is to not use Javascript at all. Will have to be aware and reactive toward the usecases though.

**Comment by lunny** [comment]
OKay. But if you can public a javascript method to call Go method. It's also resolve the problem.

**Comment by influx6** [comment]
I think it would be interesting if we can expose a rpc like objection. Which will call the javascript with the necessary argument

**Comment by maxence-charriere** [comment]
This will handle by [syscall/js](https://golang.org/pkg/syscall/js/).
See: https://github.com/murlokswarm/app/issues/262
