### ISSUE TITLE
Linux and Windows compatible

### ISSUE THREAD

**Issue by DblK** [murlokswarm/app#210]
I just found out this project and I wanted to point out to you this one : https://github.com/zserge/webview

It's a single header file that also a webview for linux, macos and windows. It's a tiny core but missing some stuff to build a full desktop app. Looking at your project, it seems that you already have a bunch of stuff working including, dock, menu, etc..

To speed up your windows and maybe later linux compatibility, maybe have a look ;)

Feel free to close this issue ;)

**Comment by maxence-charriere** [comment]
Thanks for the suggestion. 

I already took a look on this a while ago. Was pretty interesting but the problem i have with windows is that its based on the old IE browser.
Look like this the past for Microsoft and their efforts are on improving edge html.

I ll definitely take a look again when I ll start Linux driver though.

**Comment by DblK** [comment]
Okay. No problem I just point out to help you if you need to.
Looking a Windows I know that relying or MSHtml instead of EdgeHtml is not the better thing to do. However Edge doesn't not (yet) allow to embed webview without doing some extra stuff (I will edit and point out some doc).
But it's a concern for the library and there are trying to have edge and ie as fallback on windows. 

Great work and I hope you will find a solution.
