### ISSUE TITLE
Is it possible to subscribe to multiple events?

### ISSUE THREAD

**Issue by emersonian** [murlokswarm/app#214]
Hi, I just started playing with your framework yesterday and it's a lot of fun. Great job, thank you for open sourcing it. The documentation is pretty sparse (in English at least), I'd love to send some pull requests to help improve it. Events and actions are the most confusing area in my opinion.

Is it possible for a Compo to subscribe to multiple events? I am currently creating more Compos than I probably need to in order to subscribe to several different things.

Example, how would this subscribe to two events with two handlers?

```
func (l *ClickListener) Subscribe() *app.EventSubscriber {
	return app.NewEventSubscriber().
		Subscribe("click-event", l.OnClickEvent)
}
```

**Comment by maxence-charriere** [comment]
It is possible. You have to chain the Subscribe calls:

```go
	return app.NewEventSubscriber().
		Subscribe("click-event", l.OnClickEvent).
		Subscribe("eventA", l.HandlerA).
		Subscribe("eventA", l.HandlerABis).
		Subscribe("eventB", l.HandlerB)
```

Maybe this syntax is not obvious at all. Let me know if you have better suggestions.
