### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by gedw99** [murlokswarm/app#220]
Can you add printing ?

I think there are a few libs out there to support this in general, but for webviews maybe they have their own API calls ?

**Comment by gedw99** [comment]
I found the golang lib for Printing on windows: https://github.com/alexbrainman/printer
It works for me, but is very simple.

Its using this Windows API, so cgo :)
https://docs.microsoft.com/en-us/windows/desktop/printdocs/printing-and-print-spooler-reference

**Comment by gedw99** [comment]
I now realise its better to go native since thats what you have done for WIndows uwp repo.

Code sample for UWP printing. Not sure if its petinet to web based UWP ?
https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/print-from-your-app

**Comment by maxence-charriere** [comment]
I think on Mac you can already do this by providing a menu button that have a `selector="print:"`.
That would be good to this button in the default menu bar though.

**Comment by gedw99** [comment]
wow how on earth do you know all these little details. I could not find that trick anywhere on google.
I will try it here on one of the demos and see how it goes

**Comment by gedw99** [comment]
I changed this line: https://github.com/murlokswarm/app/blob/master/examples/menu/menu.go#L36
 to add the extra menu item for printing. But it prints 2 blank pages and not the actual window. Any ideas ?

````
<menu label="Custom">
	<menuitem label="Print" keys="cmdorctrl+p" selector="print:"></menuitem>
	<menuitem label="MenuItem with Go callback" onclick="OnClick"></menuitem>
	<menuitem label="MenuItem with icon" onclick="OnClickWithIcon" icon="logo.png" checked></menuitem>
	<menuitem label="MenuItem with keys" keys="cmdorctrl+e" onclick="OnMenuItemWithShorcutClick" checked></menuitem>
	<menuitem separator></menuitem>
	<menuitem label="MenuItem disabled" onclick="OnClick" disabled="true"></menuitem>
</menu>
	`
````

**Comment by maxence-charriere** [comment]
Did you launch it from the window or the menubar?
If not from the menubar could you try it?

**Comment by gedw99** [comment]
i launched it from the menu bar. I assume then it should have worked.
Maybe the page needs a print style sheet ?

**Comment by maxence-charriere** [comment]
Don't now, have to do some tests
