### ISSUE TITLE
make screenshot

### ISSUE THREAD

**Issue by gedw99** [murlokswarm/app#221]
It would be nice to have a button to take screen shots in the app itself. This is really useful for user to report bugs, but also for the share functionality that i saw in the test app. It woudl allow you to share a screen capture as part of the URL. Just like what google hangouts does.

For now just the ability to press a button in the app and take a screen shot and then use it for whatever ( like submit a bug, etc) would be really useful.
Here is a cross platform golang lib with no cgo ! 
https://github.com/kbinani/screenshot 
I don't know if webviews have their own API for making screen shots. I expect not.

It might be very useful for testing later too. a self running test app can take screen shots as it goes through phases. The screen shots can be compared to golden images for any differences.
This is is how google test skia and the code is in golang too.
https://github.com/google/skia-buildbot/blob/master/golden/go/diff/diff.go
I am not suggesting at all that this is needed. Its too heavy right now, but maybe later.

Actually maybe this is also something that the community can make ?
Not sure yet of the architecture for how to easily add extra simple functionality like this that is independent of the low level webview stuff, but i expect its a drive interface and then an implementation.

**Comment by gedw99** [comment]
Its enough for devs, but users often dont know that.

But did you read the use cases i gave ?

1. You share a link to a route in the app, You want it to take a screenshot and the link and share it. THis is what whatsapp, google hangouts, and telegram does. Its really nice.
THen on the other users side, they get a notification ( from the same app ) and see the screenshot and link. They are now able to see what the hell your on about and why you are sharing something and click it and it routes to the right location in their app. 

2. I gave a few others but use case 1 is really a killer i think..

what ya think ?

**Comment by maxence-charriere** [comment]
This is a nice feature but this requires infrastructure. It seems to be an entire project on his own and I don't have the resources to make it happen for now.

The focus for now is to ship the multiplatform promise of this package.

**Comment by gedw99** [comment]
definitely a lot of work, but i can do all the infrastructure stuff and even make a nice demo and contribute it if you want or host it on my github.
All i need is the ability to take a screenshot.
Is that better ?

**Comment by gedw99** [comment]
ok :)
