### ISSUE TITLE
How to get a component by an id?

### ISSUE THREAD

**Issue by lunny** [murlokswarm/app#23]

**Comment by maxence-charriere** [comment]
This is not possible, components IDs are just used internally to target renderings.

**Comment by lunny** [comment]
But that's very useful when I click one button then I need refresh another component. Otherwise I don't know how to implement it.

**Comment by maxence-charriere** [comment]
can you provide a sample of your use case?

**Comment by lunny** [comment]
see https://github.com/godaily/client/blob/master/refresh.go#L40

**Comment by lunny** [comment]
And this repo cannot run normally since there a xml syntax check error on murlokswarm

**Comment by maxence-charriere** [comment]
Would it be a solution for you to use the flux package?
https://github.com/murlokswarm/flux

You could make the NewsList component register to a store and send an action in the RefreshButton.OnClick func.

Otherwise,
Can you describe how would be the ideal way for you to handle this problem?

**Comment by maxence-charriere** [comment]
Also, just to let you know that I really appreciate your feedbacks :).

**Comment by lunny** [comment]
The flux could be work background
```Go
(c *MyComponent) OnClick() {
     // get window
    componentAnother, err := win.GetComponentByID(c.AnotherComponentID)
    // do something with componentAnother
    win.Render(componentAnother)
}
```
I think the way to code is ideally because it's more similar with the previous many GUI frameworks.

**Comment by lunny** [comment]
And maybe you could implemented.
If some struct implemented the below method. It will be invoked when the component created. Then you don't need get the window every method. And this method has better performance but a bit more memory (a pointer every struct).
```Go
(c *MyComponent) SetWindow(w window) {
c.window = w
}
```

**Comment by maxence-charriere** [comment]
I think this would do the job:
```go
func ComponentByID(id uid.ID) Componer
func ComponentID(c Componer) uid.ID
```
No need to be aware of the context to have a Component ID.

Also for your problem with the xml,
try this:
```html
<li>
    <a href="{{.Url}}">{{html .Title}}</a> - {{time .Updated "2006-01-02"}}
</li>
```
That should works ;)

**Comment by maxence-charriere** [comment]
Let me know if this thing would work for you

**Comment by lunny** [comment]
`{{html .Title}}` really work. Thanks!

```Go
func ComponentByID(id uid.ID) Componer {}
func ComponentID(c Componer) uid.ID {}
```
seems great. can't wait to use the functions.

**Comment by maxence-charriere** [comment]
You can use it now
https://github.com/murlokswarm/app/pull/24

**Comment by lunny** [comment]
Yes. Great work.
