### ISSUE TITLE
use of internal package not allowed

### ISSUE THREAD

**Issue by xuange306** [murlokswarm/app#232]
我下载了murlokswarm/app放到了我的mac中, 我在执行go install时,提示我
macpkg.go:15:2: use of internal package not allowed
mac.go:12:2: use of internal package not allowed
我该怎么办?

**Comment by xuange306** [comment]
我下载了murlokswarm/app放到了我的mac中, 我在执行go install时,提示我
macpkg.go:15:2: use of internal package not allowed
mac.go:12:2: use of internal package not allowed
我该怎么办?

**Comment by xuange306** [comment]
> _No description provided._

**Comment by maxence-charriere** [comment]
I can't understand Chinese.

**Comment by xuange306** [comment]
#234
