### ISSUE TITLE
cant run the install

### ISSUE THREAD

**Issue by RichardChester** [murlokswarm/app#239]
Hello,

First just wanted to say. Massive fan of what this project is aiming to do and love the examples and doumentation that come with it. however im struggling to install it on my machine.

i type
go get -u -v github.com/murlokswarm/app/...

but I end up getting 

 go get -u -v github.com/murlokswarm/app/...
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
        ignoring ..\..\go.mod;
        see 'go help modules'
github.com/murlokswarm/app (download)
github.com/google/uuid (download)
github.com/pkg/errors (download)
github.com/disintegration/imaging (download)
Fetching https://golang.org/x/image/bmp?go-get=1
https fetch failed: Get https://golang.org/x/image/bmp?go-get=1: dial
tcp 172.217.23.17:443: connectex: No connection could be made because
the target machine actively refused it.
package golang.org/x/image/bmp: unrecognized import path "golang.org/x/image/bmp" (https fetch: Get https://golang.org/x/image/bmp?go-get=1: dial tcp 172.217.23.17:443: connectex: No connection could be made because the target machine actively refused it.)
Fetching https://golang.org/x/image/tiff?go-get=1
https fetch failed: Get https://golang.org/x/image/tiff?go-get=1: dial tcp 172.217.23.17:443: connectex: No connection could be made because the target machine actively refused it.
package golang.org/x/image/tiff: unrecognized import path "golang.org/x/image/tiff" (https fetch: Get https://golang.org/x/image/tiff?go-get=1: dial tcp 172.217.23.17:443: connectex: No connection could be made because the target machine actively refused it.)
github.com/segmentio/conf (download)
github.com/segmentio/objconv (download)
Fetching https://gopkg.in/go-playground/mold.v2/modifiers?go-get=1
https fetch failed: Get https://gopkg.in/go-playground/mold.v2/modifiers?go-get=1: dial tcp 35.196.143.184:443: connectex: No connection could be made because the target machine actively refused it.
package gopkg.in/go-playground/mold.v2/modifiers: unrecognized import
path "gopkg.in/go-playground/mold.v2/modifiers" (https fetch: Get https://gopkg.in/go-playground/mold.v2/modifiers?go-get=1: dial tcp 35.196.143.184:443: connectex: No connection could be made because the target machine actively refused it.)
Fetching https://gopkg.in/validator.v2?go-get=1
https fetch failed: Get https://gopkg.in/validator.v2?go-get=1: dial tcp 35.196.143.184:443: connectex: No connection could be made because
the target machine actively refused it.
package gopkg.in/validator.v2: unrecognized import path "gopkg.in/validator.v2" (https fetch: Get https://gopkg.in/validator.v2?go-get=1: dial tcp 35.196.143.184:443: connectex: No connection could be made because the target machine actively refused it.)
Fetching https://golang.org/x/net/html?go-get=1
https fetch failed: Get https://golang.org/x/net/html?go-get=1: dial tcp 172.217.23.17:443: connectex: No connection could be made because the target machine actively refused it.
package golang.org/x/net/html: unrecognized import path "golang.org/x/net/html" (https fetch: Get https://golang.org/x/net/html?go-get=1: dial tcp 172.217.23.17:443: connectex: No connection could be made because the target machine actively refused it.)
Fetching https://golang.org/x/net/html/atom?go-get=1
https fetch failed: Get https://golang.org/x/net/html/atom?go-get=1: dial tcp 172.217.23.17:443: connectex: No connection could be made because the target machine actively refused it.
package golang.org/x/net/html/atom: unrecognized import path "golang.org/x/net/html/atom" (https fetch: Get https://golang.org/x/net/html/atom?go-get=1: dial tcp 172.217.23.17:443: connectex: No connection could be made because the target machine actively refused it.)
package github.com/murlokswarm/app/drivers/mac: build constraints exclude all Go files in D:\Users\#rich\go\src\github.com\murlokswarm\app\drivers\mac
github.com/stretchr/testify (download)

is this because I'm trying to run this on a windows machine, appriciate the help.

thanks in advance,

Rich

**Comment by maxence-charriere** [comment]
Hello, thanks for the kind words.
You should be able to do it from a windows machine.

I think the problem is related to your go install.

Here is a couple of thing:
- What version of windows do you run?
- can you provide the output of `go env`
- try to run `go clean -mod` and relaunch `go get -u -v github.com/murlokswarm/app/...`
- can you go get another package? try  `go get github.com/pkg/errors`

I also tried to take a look on connectex issues, apparently someone got it with docker (which uses go). He solved it by reinstalling it in admin mode.

Hope it helps.
Let me know how it is going.

**Comment by RichardChester** [comment]
Thank you for getting back to me so quickly,
 
So im running windows 7 

my go env is
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=D:\Users\#richard.chester2\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Users\#richard.chester2\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=D:\Users\#richard.chester2\AppData\Local\Temp\go-build581105082=/tmp/go-build -gno-record-gcc-switches

I then ran the clean and tried the install again and got 

$ go get -u -v github.com/murlokswarm/app/...
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
        ignoring ..\..\go.mod;
        see 'go help modules'
github.com/murlokswarm/app (download)
github.com/google/uuid (download)
github.com/pkg/errors (download)
github.com/disintegration/imaging (download)
Fetching https://golang.org/x/image/bmp?go-get=1
https fetch failed: Get https://golang.org/x/image/bmp?go-get=1: dial
tcp 216.58.210.49:443: connectex: No connection could be made because
the target machine actively refused it.
package golang.org/x/image/bmp: unrecognized import path "golang.org/x/image/bmp" (https fetch: Get https://golang.org/x/image/bmp?go-get=1: dial tcp 216.58.210.49:443: connectex: No connection could be made because the target machine actively refused it.)
Fetching https://golang.org/x/image/tiff?go-get=1
https fetch failed: Get https://golang.org/x/image/tiff?go-get=1: dial tcp 216.58.210.49:443: connectex: No connection could be made because the target machine actively refused it.
package golang.org/x/image/tiff: unrecognized import path "golang.org/x/image/tiff" (https fetch: Get https://golang.org/x/image/tiff?go-get=1: dial tcp 216.58.210.49:443: connectex: No connection could be made because the target machine actively refused it.)
github.com/segmentio/conf (download)
github.com/segmentio/objconv (download)
Fetching https://gopkg.in/go-playground/mold.v2/modifiers?go-get=1
https fetch failed: Get https://gopkg.in/go-playground/mold.v2/modifiers?go-get=1: dial tcp 35.196.143.184:443: connectex: No connection could be made because the target machine actively refused it.
package gopkg.in/go-playground/mold.v2/modifiers: unrecognized import
path "gopkg.in/go-playground/mold.v2/modifiers" (https fetch: Get https://gopkg.in/go-playground/mold.v2/modifiers?go-get=1: dial tcp 35.196.143.184:443: connectex: No connection could be made because the target machine actively refused it.)
Fetching https://gopkg.in/validator.v2?go-get=1
https fetch failed: Get https://gopkg.in/validator.v2?go-get=1: dial tcp 35.196.143.184:443: connectex: No connection could be made because
the target machine actively refused it.
package gopkg.in/validator.v2: unrecognized import path "gopkg.in/validator.v2" (https fetch: Get https://gopkg.in/validator.v2?go-get=1: dial tcp 35.196.143.184:443: connectex: No connection could be made because the target machine actively refused it.)
Fetching https://golang.org/x/net/html?go-get=1
https fetch failed: Get https://golang.org/x/net/html?go-get=1: dial tcp 216.58.210.49:443: connectex: No connection could be made because the target machine actively refused it.
package golang.org/x/net/html: unrecognized import path "golang.org/x/net/html" (https fetch: Get https://golang.org/x/net/html?go-get=1: dial tcp 216.58.210.49:443: connectex: No connection could be made because the target machine actively refused it.)
Fetching https://golang.org/x/net/html/atom?go-get=1
https fetch failed: Get https://golang.org/x/net/html/atom?go-get=1: dial tcp 216.58.210.49:443: connectex: No connection could be made because the target machine actively refused it.
package golang.org/x/net/html/atom: unrecognized import path "golang.org/x/net/html/atom" (https fetch: Get https://golang.org/x/net/html/atom?go-get=1: dial tcp 216.58.210.49:443: connectex: No connection could be made because the target machine actively refused it.)
package github.com/murlokswarm/app/drivers/mac: build constraints exclude all Go files in D:\Users\#richard.chester2\go\src\github.com\murlokswarm\app\drivers\mac
github.com/stretchr/testify (download)

and tried doing a repair of my go install and then got the same again

**Comment by maxence-charriere** [comment]
are you running it from a linux subsystem ?

**Comment by maxence-charriere** [comment]
To be honest, I did not test this package on Windows 7. I don't see a reason why it would fail though.

I really think the issue does not come from this package.
Can you try to go get one of the failing dependencies?

```
got get -u golang.org/x/net/html
```
Do you have any firewall setup?

**Comment by RichardChester** [comment]
Yup there was a firewall and a few proxy setting blocking it but now there fixed I ran

`$ go get -u -v github.com/murlokswarm/app/...`

again and got the following

`github.com/murlokswarm/app (download)
github.com/google/uuid (download)
github.com/pkg/errors (download)
github.com/disintegration/imaging (download)
Fetching https://golang.org/x/image/bmp?go-get=1
Parsing meta tags from https://golang.org/x/image/bmp?go-get=1 (status code 200)
get "golang.org/x/image/bmp": found meta tag get.metaImport{Prefix:"golang.org/x/image", VCS:"git", RepoRoot:"https://go.googlesource.com/image"} at https://golang.org/x/image/bmp?go-get=1
get "golang.org/x/image/bmp": verifying non-authoritative meta tag
Fetching https://golang.org/x/image?go-get=1
Parsing meta tags from https://golang.org/x/image?go-get=1 (status code 200)
golang.org/x/image (download)
Fetching https://golang.org/x/image/tiff?go-get=1
Parsing meta tags from https://golang.org/x/image/tiff?go-get=1 (status code 200)
get "golang.org/x/image/tiff": found meta tag get.metaImport{Prefix:"golang.org/x/image", VCS:"git", RepoRoot:"https://go.googlesource.com/image"} at https://golang.org/x/image/tiff?go-get=1
get "golang.org/x/image/tiff": verifying non-authoritative meta tag
Fetching https://golang.org/x/image/tiff/lzw?go-get=1
Parsing meta tags from https://golang.org/x/image/tiff/lzw?go-get=1 (status code 200)
get "golang.org/x/image/tiff/lzw": found meta tag get.metaImport{Prefix:"golang.org/x/image", VCS:"git", RepoRoot:"https://go.googlesource.com/image"} at https://golang.org/x/image/tiff/lzw?go-get=1
get "golang.org/x/image/tiff/lzw": verifying non-authoritative meta tag
github.com/segmentio/conf (download)
github.com/segmentio/objconv (download)
Fetching https://gopkg.in/go-playground/mold.v2/modifiers?go-get=1
Parsing meta tags from https://gopkg.in/go-playground/mold.v2/modifiers?go-get=1 (status code 200)
get "gopkg.in/go-playground/mold.v2/modifiers": found meta tag get.metaImport{Prefix:"gopkg.in/go-playground/mold.v2", VCS:"git", RepoRoot:"https://gopkg.in/go-playground/mold.v2"} at https://gopkg.in/go-playground/mold.v2/modifiers?go-get=1
get "gopkg.in/go-playground/mold.v2/modifiers": verifying non-authoritative meta tag
Fetching https://gopkg.in/go-playground/mold.v2?go-get=1
Parsing meta tags from https://gopkg.in/go-playground/mold.v2?go-get=1 (status code 200)
gopkg.in/go-playground/mold.v2 (download)
github.com/segmentio/go-snakecase (download)
Fetching https://gopkg.in/go-playground/mold.v2?go-get=1
Parsing meta tags from https://gopkg.in/go-playground/mold.v2?go-get=1 (status code 200)
get "gopkg.in/go-playground/mold.v2": found meta tag get.metaImport{Prefix:"gopkg.in/go-playground/mold.v2", VCS:"git", RepoRoot:"https://gopkg.in/go-playground/mold.v2"} at https://gopkg.in/go-playground/mold.v2?go-get=1
Fetching https://gopkg.in/validator.v2?go-get=1
Parsing meta tags from https://gopkg.in/validator.v2?go-get=1 (status
code 200)
get "gopkg.in/validator.v2": found meta tag get.metaImport{Prefix:"gopkg.in/validator.v2", VCS:"git", RepoRoot:"https://gopkg.in/validator.v2"} at https://gopkg.in/validator.v2?go-get=1
gopkg.in/validator.v2 (download)
Fetching https://golang.org/x/net/html?go-get=1
Parsing meta tags from https://golang.org/x/net/html?go-get=1 (status
code 200)
get "golang.org/x/net/html": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/html?go-get=1
get "golang.org/x/net/html": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code
200)
golang.org/x/net (download)
Fetching https://golang.org/x/net/html/atom?go-get=1
Parsing meta tags from https://golang.org/x/net/html/atom?go-get=1 (status code 200)
get "golang.org/x/net/html/atom": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/html/atom?go-get=1
get "golang.org/x/net/html/atom": verifying non-authoritative meta tag
package github.com/murlokswarm/app/drivers/mac: build constraints exclude all Go files in D:\Users\rich\go\src\github.com\murlokswarm\app\drivers\mac
github.com/stretchr/testify (download)`

that all looks fine to me everything installed and all the dependencies there, but when I run

` $ goapp update -v`

I still get 

`bash: goapp: command not found`

**Comment by maxence-charriere** [comment]
is %GOPATH%\bin is in your PATH env variable?
(Also no sure if it is the env syntax on windows, you may have to put the full path in)

**Comment by RichardChester** [comment]
running the go env returns:

`$ go env
set GOARCH=amd64
set GOBIN=D:\Users\richard.chester2\go\bin
set GOCACHE=D:\Users\richard.chester2\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Users\richard.chester2\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=D:\Users\richard.chester2\AppData\Local\Temp\go-build868131826=/tmp/go-build -gno-record-gcc-switches`

**Comment by RichardChester** [comment]
I think that means my GOBIN is setup right ?

**Comment by maxence-charriere** [comment]
I think the gobin is where the go binaries are. Its the bin of your gopaht that must be added into you path environment variable.

**Comment by RichardChester** [comment]
Hi 

I eventually managed to get it working by using go build and moving the binary into GOBIN but now I'm getting a new error

when it try and run `goapp web build` or `goapp web run` from inside the directory it returns `x exec: "gopherjs": executable file not found in %PATH%` it creates a .wapp file with a .exe inside it but when i run that .exe i just get a blank page when I was expecting the hello world example

**Comment by maxence-charriere** [comment]
have to run `go web init first`

**Comment by RichardChester** [comment]
sorry I should have mentioned that I've been doing that,

so I cd into directory and run `go web init`

I then create a main.go file with all the code in it (I've been using the example "hello")

I then have a resources folder with the css in it and a main.go file I then run `goapp web build`

then when I try and run it I get the message `"gopherjs": executable file not found in %PATH%`

thank you for your continued help

**Comment by maxence-charriere** [comment]
Would need more info:
- Launch `cmd.exe`
- Enter `SET path`
- Copy/Paste the output here

**Comment by RichardChester** [comment]
when I run the app from the bash terminal

`$ ./hello-web.exe
LOG 2018/12/29 21:51:23 ‣ running *web.Driver driver
LOG 2018/12/29 21:51:32 ‣ serving /hello.Hello
LOG 2018/12/29 21:51:32 ‣ serving /web.NotFound
LOG 2018/12/29 21:51:41 ‣ serving /hello.Hello
LOG 2018/12/29 21:51:42 ‣ serving /hello.Hello
LOG 2018/12/29 21:51:43 ‣ serving /hello.Hello`
