### ISSUE TITLE
How to run the second window?

### ISSUE THREAD

**Issue by lunny** [murlokswarm/app#25]
It seems the second window cannot show.

**Comment by maxence-charriere** [comment]
```WARN  2017/02/04 10:17:08 call.go:26: *main.AppMainMenu doesn't have a method named```
```go get -u github.com/murlokswarm/mac``` should solve your problem.

**Comment by maxence-charriere** [comment]
Hey @lunny, did this solved your problem ?

**Comment by lunny** [comment]
Yes. Thanks!
