### ISSUE TITLE
[ Query for Ubuntu 16.04]

### ISSUE THREAD

**Issue by vikaskyadav** [murlokswarm/app#26]
Is it available for Ubuntu 16.04 LTS ? Plus,  in case you need UI/UX designing/development work, I am willing to contribute.

**Comment by maxence-charriere** [comment]
Hey @vikaskyadav, thanks for the interest.
This is currently available only on MacOS.

The framework is designed to be multiplatform though.
Any implementation of the [app.Driver](https://godoc.org/github.com/murlokswarm/app#Driver) interface would work.

I'm currently working on improving the base package and bringing this on Windows.
But it's already a lot of work to do in my free time.

Contributions to build drivers for other platforms are welcome and I would be glad to help.

**Comment by maxence-charriere** [comment]
Just set a repo for this https://github.com/murlokswarm/linux

**Comment by vikaskyadav** [comment]
Awesome. I haven't done any work on Go but surely would like for Linux driver development if get chance to do so.

**Comment by lunny** [comment]
Maybe linux-webKit since there is not a default GUI and web browser.
