### ISSUE TITLE
Mobile performance?

### ISSUE THREAD

**Issue by mochacoder** [murlokswarm/app#29]
I'm wondering how this will perform on iOS and Android once it's possible to build for those platforms. Is there any way to get a development build on mobile to see performance there, what parts are required if I wanted to try and work on it?

**Comment by maxence-charriere** [comment]
Drivers for these platforms have to be built.
This is planned but this project is built as a side project on my free time. I'm working right now on the Windows driver. IOS or Android will be the next one.

I believe performances would be acceptable on the latest phones, they became pretty powerful and the approach of the package is to keep the web view only for the UI. All the rest is done with Go, which pretty performant and native.

**Comment by maxence-charriere** [comment]
Hey @mochacoder.
This will be relevant when a mobile driver will be available.
Gonna close it for the moment.
