### ISSUE TITLE
Application fail without logs

### ISSUE THREAD

**Issue by ScullWM** [murlokswarm/app#33]
Hi,

I've made a small app using this (great) tool, and I get a strange bug.
If I build the app and start the executable (`go build && ./client-macos`), there's a prompt that open, with all the log in, and the real app (with nice macos UI). Application work well and logs are also stored in log file.
![](http://www.updemia.com/static/e/b/xl/58b5dd1b238fd.png)

Troubles start when I start using macpack (`go build && macpack build`). App doesn't start and I get no logs in my logfile. I don't understand why.
Is there a special tricks to have logs? Many thanks!

GO-ENV
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/thomasp/Golang"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2n/1p_pny6x2p180gcj7kkbwz0c0000gn/T/go-build479332264=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
![Uploading Capture d’écran 2017-02-28 à 21.26.59.png…]()

```

**Comment by maxence-charriere** [comment]
what command do you try to start the ?

**Comment by maxence-charriere** [comment]
Can you copy/paste the macpack output and how you try to launch the app?

**Comment by ScullWM** [comment]
Here's the mac.json file content:
```
{
  "name": "Updemia",
  "id": "updemia.client",
  "version": "1.0",
  "build-number": 1,
  "icon": "logo2.png",
  "dev-region": "en",
  "deployment-target": "10.12",
  "copyright": "Copyright © 2017 scullwm. All rights reserved",
  "role": "None",
  "category": "",
  "sandbox": true,
  "capabilities": {
    "network": {
      "in": false,
      "out": true
    },
    "hardware": {
      "camera": false,
      "microphone": false,
      "usb": false,
      "printing": false,
      "bluetooth": false
    },
    "app-data": {
      "contacts": false,
      "location": false,
      "calendar": false
    },
    "file-access": {
      "user-selected": "/Users/thomasp/updemia/",
      "downloads": "",
      "pictures": "",
      "music": "",
      "movies": ""
    }
  },
  "store": false,
  "sign-id": "",
  "supported-files": []
}
```
I think that it can be a folder access restriction that block app from launch...
Note that the application is currently using `github.com/howeyc/fsnotify` to check events that happen in the folder `/Users/thomasp/updemia/`. This folder is so declared in the file-access.user-selected node.

**Comment by maxence-charriere** [comment]
the app is running in sandbox box mode right now, which allow to access only restricted area.
try by setting ``` "sandbox": true,```  in your mac.json.

**Comment by maxence-charriere** [comment]
Hey @ScullWM,
Was you able to fix that?

**Comment by maxence-charriere** [comment]
close this one, reopen if needed.
