### ISSUE TITLE
handle applinks

### ISSUE THREAD

**Issue by themihai** [murlokswarm/app#34]
I'm trying to handle application links but there doesn't seem to be any documentation on how to do it(i.e. capture the request and display a new scene/page). The app logs two errors: 

Received an unexpected URL from the web process: 'file://www.w3schools.com/'
Received an invalid message "WebPageProxy.DecidePolicyForNavigationAction" from the web process.

```

package main

import "github.com/murlokswarm/app"

// Hello implements app.Componer interface.
type Hello struct {
	Greeting string
}

// Render returns the HTML markup that describes the appearance of the
// component.
// It supports standard HTML and extends it slightly to handle other component
// declaration or Golang callbacks.
// Can be templated following rules from https://golang.org/pkg/text/template.
func (h *Hello) Render() string {
	return `
<div class="WindowLayout" oncontextmenu="OnContextMenu">    
    <div class="HelloBox">
        <h1>
        <a href="//www.w3schools.com">Visit W3Schools</a>
Try it Yourself »

            Hello,
          <span>
                {{if .Greeting}}
                    {{html .Greeting}}
                {{else}}
                    World
                {{end}}
            </span>
        </h1>
        <input type="text"
               value="{{html .Greeting}}"
               placeholder="What is your name?"
               autofocus="true"
               onkeydown="Greeting"
               onkeyup="Greeting"
               onchange="OnInputChange" />
    </div>
</div>
    `
}

// OnInputChange is the handler called when an onchange event occurs.
func (h *Hello) OnInputChange(arg app.ChangeArg) {
	app.Render(h) // Tells the app to update the rendering of the component.
}

// OnContextMenu is the handler called when an oncontextmenu event occurs.
func (h *Hello) OnContextMenu() {
	ctxmenu := app.NewContextMenu()
	ctxmenu.Mount(&AppMainMenu{})
}

func init() {
	// Registers the Hello component.
	// Allows the app to create a Hello component when it finds its declaration
	// into a HTML markup.
	app.RegisterComponent(&Hello{})
}

```

**Comment by maxence-charriere** [comment]
should it be just ```http://www.w3schools.com``` ?

**Comment by themihai** [comment]
Currently href="http://www.w3schools.com" opens up safari in a new window. Is there any way we can trap/catch the link requests into the application?  I'm would like to  use links/hrefs to manage the UI in the stateless manner(i.e. like a http server).

**Comment by joeblew99** [comment]
I hit the same thing.
We need to use Url schemes / intents to fix this and also all the other UX aspects of communications between GUI windows.
I wrote a basic proposal here:
https://github.com/murlokswarm/app/issues/38

**Comment by maxence-charriere** [comment]
@themihai, this is a normal behavior. Such a link is opened in the default browser in order to not mess with the app navigation (which already run into a browser).

I'm not sure to understand what you trying to do though.
Url should be for navigate to another page or another app.

This package is built on the top of a web view but it is not intended to be used a fully featured web browser.

The idea is just to describe the UI with HTML/CSS.  Any other tasks should be done with Go.

**Comment by themihai** [comment]
We have two issues more or less related:
- Custom URI schema:
     I've seen your comment on https://github.com/murlokswarm/app/issues/38 but it's still not clear to me how you can handle the custom URI scheme requests to your app. e.g. if someone links my app (e.g. myapp://someurl/?q=xyz) how do I know the URL path/params? 
 https://github.com/skratchdot/open-golang just allows you to open other apps using custom URI scheme not to handle requests to yours.

- Navigation to other URLs:
hrefs are part of the HTML spec so I think we should be able to use them for navigation within our app if we want /need to(.e.g  from one page/screen to another one).  However the "navigation router" should  be part of various frameworks not murlokswarm engine itself.
 The murlokswarm engine should provide an API / callback/channel  intercept the URL/Href requests from our app. Basically when the client clicks on a URL from our app we need receive a callback so that we  handle the request(i.e. we may want to open it in a new window with the default browser<current behaviour>, or show an error message or do something else) Both webkit and IOS webview support this( https://developer.apple.com/reference/webkit/wknavigationdelegate). I think the error itself says which API need to be implemented/hooked ( WebPageProxy.DecidePolicyForNavigationAction).

**Comment by maxence-charriere** [comment]
- I see what you mean for the custom URI schema. I will look into it to see how to handle that.

- For the second request, that is a very big change.
The couple window/webview acts as a generic context which mounts and renders a component.
A page is not a component. Even if we allow to navigate to the web page, how to go back to the interface?
We could provide a way to do previous or next but it imply a lot more of complexity to handle in a generic way components and normal html pages.
This task cannot be done with a little fix. It requires to be well prepared in order to have a good implementation.
Will add it on my todo list but I can't guarantee you when this will be available.

**Comment by themihai** [comment]
>>  Even if we allow to navigate to the web page, how to go back to the interface?

Technically all I'm asking is a global function <e.g. app.OnHref(url *url.URL) )> akin to app.OnLaunch,app.OnBlur etc which should be executed by the engine whenever the client clicks on a href.  Basically instead to open the link in new window like it currently does the engine should execute/call ``app.OnHref`` and let the developer decide the behaviour. The developer may render whatever it wants regardless if the component is related semantically to the href the client "clicked". For example when it clicks on "http://google.com" the developer may choose to display/render a custom component that is using the google API or just show a "google" logo.  The point is that  "navigation" would be handled internally by the developer. The "href" element would simply serve as  "reference/link" for the developer to render various components. It would also make the app more web-like and potentially more portable.
 Below is some pseudo code. Let me know if it makes sense to you:


```
var win app.Windower

func newWindow() {
	win = app.NewWindow(app.Window{
		Title:          "Hello World",
		Width:          1280,
		Height:         720,
		TitlebarHidden: true,
	})
}

func main() {

	app.OnLaunch = func() {
		wind = newWindow()
		home := &Home{}
		win.Mount(home)
	}
	// app.OnHref listens for click on href events and executes handleRequest
	app.OnHref = listenOnHref
	// start the app
	app.Run()
}


// listenOnHref helps you implement custom behaviors that are triggered 
// when a client clicks on a "href" element. 
// This should be assigned to app.OnHref to overwrite the default policy (opening the href in a new window with the default browser)
func listenOnHref(url *url.URL) {
	//Create a  listener which listens for click on hrefs.
	ln := murlokswarPkg.NewListener()
	// Continously listen for new requests/WebPageProxy.DecidePolicyForNavigationAction notifications
	// On each new request we redraw the entire Window(e.g. account page,
	// home page, videplayer page etc) 
	// so on each new request repaint the window.

		// Basic UI routing based on the URL request
		switch URL.Path {
		case URL.Host != "" : 
			// Absolute hrefs should be opened in the default browser using 
			// https://github.com/skratchdot/open-golang. This is the current behaviour of murlokswarm
			// so it's emulated here for completness. 
			// In the future we may want to display a "webview" with custom navigation
			// so that the client stay remain in our app while navigating web content(i.e. like twitter does). 
			open-golang.Open(URL.String())
		case "/account":
			// Destroy/Reset/Close the current Window.
			// Perhaps we should close it more elegantly(i.e. using a transition) but I think
			// we need additional hooks into the engine  so that we can do some  pre-rendering to make it smooth

			// This looks like the only way to destroy a window 
			// and replace it, not sure if it's safe...
			win = newWindow() 
			// Launch/render a completely new window
			account := &account{}
			win.Mount(account) // I can't find any method to Mount
		case "/home":
			// Destroy the current Window
			win = newWindow() 
			// launch/render the home page
			home := &Home{}
			win.Mount(home)
		default: // unknown pages/requests
			// Destroy the current Window
			win = newWindow() 
			// launch/render the 404 page which display a "Not found" error along with a navigation bar
			// so that the client can return to the previous request. We basically handle an error
			// in the markup.
			nf := &NotFound{}
			win.Mount(nf)	
		}


}

type Home struct {
	Greeting string
}

func (h *Home) Render() string {
	return `
     Navigation:
    <a href="/home">Homepage</a>
    <a href="/account"> Account page </>
    <a href="http://www.google.com/"> Go to Google </>
<div class="WindowLayout">    
    <div class="HomeBox">
        <h1>
            Welcome Home,
            <span>{{if .Greeting}}{{html .Greeting}}{{else}}World{{end}}</span>
        </h1>
        <input type="text" placeholder="What is your name?" onchange="OnInputChange" />
    </div>
</div>
    `
}

func (h *Account) Render() string {
	return `
    Navigation:
    <a href="/home">Homepage</a>
    <a href="/account"> Account page </>

<div class="WindowLayout">    
    <div class="AccountBox">
        <h1>
            Welcome to the account page,
            <span>{{if .Greeting}}{{html .Greeting}}{{else}}World{{end}}</span>
        </h1>
        <input type="text" placeholder="your name" onchange="OnInputChange" />
    </div>
</div>
    `
}

func init() {
	app.RegisterComponent(&Home{})
	app.RegisterComponent(&Account{})
}

```

**Comment by maxence-charriere** [comment]
it's what i though for handling call from a uri scheme.

The idea for the page navigation looks interesting.
Something like that should be at the window level though.
The way it is described excludes multiple window scenario.
Gonna work on this issue this weekend.

Thanks for the feedback :)

**Comment by themihai** [comment]
I think it could work with multiple Windows too but OnHref should provide the "referer" of the  window where the client comes from just like a browser provides a "referer". A developer could keep track of all the windows and internally figure our which one needs to be changed based on the referer.  
```
e.g. 

var windows []Window // all the windows should be managed here

type OnHrefFunc func(url *net.URL, referrer  string)

// listen on href events
func listenOnHrefs(url *net.URL, referrer string), 
   for _, window := range windows{
      if window.ID  == referrer{ // we found the window we need to update
            // do the routing
            routeReq(url , window)
      }

  }
}

func routeReq(url *net.URL, window app.Window){
      switch url.Path{
     case "/account":
            window = nil
            window.Mount(&Account{})
      ............................
}



```

**Comment by themihai** [comment]
Another option for the multi window issue would be for the OnHref function to provide the Window object itself(instead the referer). The engine "knows" the window where the client clicks anyway.  That way the developer doesn't need to keep track of all the windows. 

e.g. 
```
type OnHrefFunc func(url *net.URL, win  *app.Window)

```

**Comment by maxence-charriere** [comment]
Hey @themihai 
You can now handle opening via url scheme.
See OnURLOpen in https://godoc.org/github.com/murlokswarm/app#pkg-variables

**Comment by joeblew99** [comment]
@maxence-charriere that was quick - will give it a whirl

**Comment by joeblew99** [comment]
wondering if the examples should show off any of this so people realise what the framework is capable of quickly ?

**Comment by maxence-charriere** [comment]
yeah it would be cool to have a series of small examples with a name reflecting what we trying to do. It's in my todo list but It so hard to handle everything ^^.
I would also like to refactor the go doc. The wiki is cool but it so pain in the ass the modify rather than just modify the comment above the code.

**Comment by maxence-charriere** [comment]
Hey @themihai 
Here is the implementation for href navigation.

```html
<a href="MyComponent">Link</a>
```

```MyComponent``` will be mounted into the window where the A tag was.
Note that ```MyComponent``` must be registered with [RegisterComponent](https://godoc.org/github.com/murlokswarm/app#RegisterComponent).

You can also implement the [Hrefer](https://godoc.org/github.com/murlokswarm/app#Hrefer) interface in your component to handle stuff when you navigate.

```go
func (c * MyComponent) OnHref(URL url.URL) {
	log.Info(URL)
}
```
This can allow to handle thing like url parameters
```html
<a href="MyComponent?customParam=hello">Link</a>
```
see https://golang.org/pkg/net/url/#URL for deal with whatever you want.

Other kind of urls (http://, https://, uri scheme, ...) will be launched with the default app assigned in the OS.
e.g. Chrome for http.

**Comment by themihai** [comment]
That's awesome! I will give it a try later today. Any reason to use url.URL instead of a pointer (*url.URL)? It may not be a big deal in terms of memory usage but it would make it more in line with the standard library/practice.

**Comment by maxence-charriere** [comment]
👍 
@themihai updated

**Comment by joeblew99** [comment]
Yeah about the docs.

Much better to just have an examples folder and basic md files as docs.
Putting them with a few examples makes it easy for users & code maintainer. Drop the wiki then.


The godoc are secondary imho.
Once people see examples then they get it.
And people can merge new examples too and it just gets better automatically
