### ISSUE TITLE
DOM Access

### ISSUE THREAD

**Issue by themihai** [murlokswarm/app#37]
Is it possible to get DOM access though w3c/standard APIs [activeElement](https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement) or any kind of low level API (i.e. like golang.org/x/net/html ) ?

**Comment by maxence-charriere** [comment]
Not yet, I planed to provide such a thing but it gonna come later. For the moment I m working on the Windows driver.

**Comment by maxence-charriere** [comment]
You gonna have to deal with html events to detect such a changes.

**Comment by themihai** [comment]
Would be possible to provide a global generic function `OnEvent(v *Event, node *app.DOMElement)` which should be called on any / all the dom events? 

We could build a mux/router on top of it to just like on Hrefer.   It is quite hard if not impossible to develop interactive applications without DOM events, only with "onchange". For example to "emulate" the functionality of [activeElement](https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement) I would have to add `"onfocus"`(an event not supported yet by murlokswarm either) on all the html elements that can receive focus. 

I believe the code would  also become easier to maintain as we can use an [unobstructive](https://en.wikipedia.org/wiki/Unobtrusive_JavaScript) approach to handle the events. The "listeners" would be created on top of "OnEvent"

**Comment by maxence-charriere** [comment]
Why the need of that?
You can currently write any function handler with an argument within a component and what you send from javascript will be unserialized in this argument.

**Comment by maxence-charriere** [comment]
Also I think ```on focus``` is supported. Just tried it.
Any dom event is redirect if you provide a handler.
