### ISSUE TITLE
Feature Proposal: Intents

### ISSUE THREAD

**Issue by joeblew99** [murlokswarm/app#38]
We need a way to allow an App to communicate with another app.
This is because a good User Experience requires the ability for the User to see two windows at once.
But its also a good pattern of modularity, and also allows you to send things to Application outside of your Apps. 

Url-scheme is a pretty good way to model this, because you can add an action and the data to the URL.

Use Cases:  
Calling external Apps.
For example if you have a google maps URL in your app, when the user clicks it you want it to open Google Maps (if its installed) OR open the google maps web page.

Calling your own Apps.
Likewise, if a user is sent an email with a link, you want them pressing the link to either open your application (if its installed) or fallback to open the your web site.

If the called App is already open, it should it open a new Window ? Not sure..

All Golang based frameworks can use this. QT, WebViews, Shiny on Desktops and Mobiles.
I think it should be written as a package, so other golang GUI frameworks can leverage it.

I started to write IOS code for this here:
https://github.com/gu-io/gu-x/tree/master/_examples/gui-intents/osx

Writing implementations for Windows, IOS, Android, etc should not be too hard.
For a developer, it can be agnostic to OS and just work.

Is this something we want to use in murlok ?

**Comment by maxence-charriere** [comment]
I have the feeling you could you use https://golang.org/pkg/os/exec/#Command with ```open``` as first param and the url as second one.
```go
func TestOther(t *testing.T) {
	cmd := exec.Command("open", "github-mac://openRepo/https://github.com/murlokswarm/app")
	if err := cmd.Start(); err != nil {
		t.Error(err)
	}
}
```

I also found this package which seems to wrap the thing to have it in one line:
 https://github.com/skratchdot/open-golang

**Comment by joeblew99** [comment]
@maxence-charriere 
very true.
i am not worried about elegance write now.
I am more about just wanting to get a standard pattern going, and examples for each OS to know we can do it.

I saw the other discussion and i agree with you - this should be all at the window level.
This is also how its designed on ios and android too, so we shoudl follow their pattern and no reinvent anti patterns.

I woudl like to consolidate work here.
I use therecipe/QT, and Murlok. Both can use this code for sure.
Gu-x is only for risky experiments i and collabs do.
So what repo to put this code in ? Have a think about it.

**Comment by maxence-charriere** [comment]
Hey @joeblew99, now apps can be opened by url scheme.

**Comment by maxence-charriere** [comment]
I close this one. Feel free to reopen if you have other concerns

**Comment by joeblew99** [comment]
just saw it. Nice one @maxence-charriere

**Comment by joeblew99** [comment]
I just heard back from the guy in charge of this at Google.
Everyone has apparently agreed that the way forward is this:

https://developers.google.com/web/updates/2016/10/navigator-share

It's in chrome but i need to check WebKit and edge
