### ISSUE TITLE
Mapping custom html attributes to go argument callbacks

### ISSUE THREAD

**Issue by icearith** [murlokswarm/app#39]
```
<ul>
<li>a</li>
<li>b</li>
</ul>
```

**Comment by maxence-charriere** [comment]
pick any html event and put the component field name or method name as a value.

**Comment by icearith** [comment]
@maxence-charriere Many thanks.

**Comment by icearith** [comment]
sorry for bothering. Can I pass data to OnLiClick? or is there any other way to achieve this feature. I need to know which item in the list is clicked.

**Comment by maxence-charriere** [comment]
Hum ok, I understand the problem. I have an idea of how we could achieve that.
Give me a little time to hack that thing, I will try to make it happen for tomorrow or after tomorrow :).

**Comment by icearith** [comment]
Wait for your good news:)

**Comment by icearith** [comment]
@maxence-charriere is it easy to map html attributes? I am currently working on a small desktop app. I have very little experience on webkit and golang. So I will try to help you.

**Comment by maxence-charriere** [comment]
Hey @icearith just merges modifications on https://github.com/murlokswarm/app/pull/41.

So now, event arg in go have a ```Target``` field that contains info about the element that emitted the event.
You in HTML could use ```id``` or ```data-murlok-index``` to help you identify which element fired the event.
In the go side, you can access by your ```arg.ID``` or ```arg.Index```.

Hope this will be enough to solve you problem.

**Comment by icearith** [comment]
Really thank you! So you can close this issue!

**Comment by icearith** [comment]
```
handler.go:35: unable to call OnLiClick: unmarshal {"AltKey":false,"Button":0,"ClientX":178,"ClientY":235,"CtrlKey":false,"Detail":1,"MetaKey":false,"PageX":178,"PageY":235,"ScreenX":613,"ScreenY":258,"ShiftKey":false,"Target":{"ID":null,"Class":null,"Index":"0","Value":0,"Tag":"li"}} failed: json: cannot unmarshal number into Go struct field DOMElement.Value of type string
```

it seems that there is a error when encoding json to go struct. 

`value` should be string.

**Comment by maxence-charriere** [comment]
yes, will be fixed in a few hour :)

**Comment by maxence-charriere** [comment]
@icearith it is fixed.
Thanks for the feedback.
Gonna close this one.
