### ISSUE TITLE
How to open a dialog to open a file

### ISSUE THREAD

**Issue by icearith** [murlokswarm/app#40]
I read the wiki and did not find any examples.

**Comment by maxence-charriere** [comment]
adding it to the todo list of this weekend.

**Comment by icearith** [comment]
@maxence-charriere Hi bro, how about the progress of this feature?

**Comment by maxence-charriere** [comment]
on it

**Comment by maxence-charriere** [comment]
Hello @icearith 
Sorry for the delay,
Just updated with the implementation.

here is how to use it:
```go
	app.NewFilePicker(app.FilePicker{
		MultipleSelection: false,
		NoDir:             true,
		NoFile:            false,
		OnPick: func(filenames []string) {
			// handle files
		},
	})
```

**Comment by icearith** [comment]
@maxence-charriere I am really interested in this project. Thank you, I am using this framework on a small personal project. I will try to help because I have very little know on front-end and macOS.
