### ISSUE TITLE
[Propose] View concept and navigations between views.

### ISSUE THREAD

**Issue by lunny** [murlokswarm/app#42]
I proposed make a `view` concept. There are already `window` and `component`, but there is no `view`. A `view` likes the similar concept on MFC/android/IOS.
A `view` is the current render display layer of a `window`, a `window` should mount a `view` but not a `component`. A `view` interface will include `component` interface but should have more method i.e. `Title() string`. You can defines many `view`s on a `window` but always only 1 will be rendered. A `window` has a navigation, a navigation is a stack of `view`s. you can push a new `view` or pop a `view` or return to any the old `view`.

For example:

Suppose we have two views: `LoginView`,  `MainView`.
When the window open, I mounted `LoginView`, and user could input name and password. When click the `login` button, we can switch it to `MainView` if he submit the correct name and password.

**Comment by maxence-charriere** [comment]
I also thought about it but I'm still undecided.

I love the fact that you interact with a window in the same flavor as the other contexts.
Introducing the view concept bring a new layer for the window and the way it work would be a little bit different.

https://github.com/murlokswarm/app/issues/34 gave me some ideas about how to handle navigation with the current implementation.
The use case you gave would work too.

Could you give me a list of pros ?
Also if there is other followers that have an idea about this, feel free to give your feedbacks too.

**Comment by lunny** [comment]
I just write some codes for `Viewer`
```Go
type Viewer interface {
	app.Componer
	Name() string
}

type Navigator struct {
	win   app.Windower
	views []Viewer
}

func NewNavigator(win app.Windower) *Navigator {
	return &Navigator{
		win: win,
	}
}

func (n *Navigator) GoBack() {
	if len(n.views) <= 1 {
		return
	}
	n.views = n.views[:len(n.views)-1]
	n.win.Mount(n.views[len(n.views)-1])
}

func (n *Navigator) GoView(view Viewer) {
	for i, p := range n.views {
		if p.Name() == view.Name() {
			n.views = n.views[:i]
			n.win.Mount(view)
			return
		}
	}

	n.views = append(n.views, view)
	n.win.Mount(view)
}
```

**Comment by themihai** [comment]
For what is worth I'm planning to develop a router/navigator on top of `app.Hrefer` `Component.Render` and a virtual dom. I believe we should embrace the DOM/HTML and try to build on top of it.
