### ISSUE TITLE
Installation fails in OSX: error: use of undeclared identifier 'NSEventModifierFlagCommand'

### ISSUE THREAD

**Issue by pakalvoltan** [murlokswarm/app#46]
Hello,
Thanks for the work and effort you have placed on developing this.
I am trying to use the software, but the installation fails.

$ go get github.com/murlokswarm/mac
# github.com/murlokswarm/mac
../github.com/murlokswarm/mac/menu.m:138:41: error: use of undeclared identifier 'NSEventModifierFlagCommand'
../github.com/murlokswarm/mac/menu.m:140:41: error: use of undeclared identifier 'NSEventModifierFlagControl'
../github.com/murlokswarm/mac/menu.m:142:41: error: use of undeclared identifier 'NSEventModifierFlagOption'
../github.com/murlokswarm/mac/menu.m:144:41: error: use of undeclared identifier 'NSEventModifierFlagShift'
../github.com/murlokswarm/mac/menu.m:146:41: error: use of undeclared identifier 'NSEventModifierFlagFunction'

I do have OSX Version 10.11.6 (15G1421)

and Xcode Version 8.2.1 (8C1002)

**Comment by maxence-charriere** [comment]
Hi @pakalvoltan
Can you copy past your env?

**Comment by pakalvoltan** [comment]
Hi,
here the ouput of my env (with login name obfuscated :) )

$ env
TERM_PROGRAM=Apple_Terminal
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/m7/4gjm2kqd2kz3vnp0pqdzjf_w0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.w92QsXtf5F/Render
TERM_PROGRAM_VERSION=361.1
TERM_SESSION_ID=DAE67F77-91E3-41B6-8D6C-2B217DCFEC31
USER=xxxxx
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.RyaFSEV3xo/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/data/code/gows/src/
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
HOME=/Users/xxxxx
SHLVL=1
LOGNAME=xxxxx
LC_CTYPE=UTF-8
GOPATH=/data/code/gows
SECURITYSESSIONID=186a6
_=/usr/bin/env

**Comment by maxence-charriere** [comment]
Oh problem come from MacOS version. You are on el capitan.
I developed it on Sierra and look like Apple did a lot of deprecation in their API.
See https://developer.apple.com/reference/appkit/nseventmodifierflags

The easy way to go is update to MacOS Sierra.

**Comment by pakalvoltan** [comment]
Thanks for the reply. For reasons not under my control, I can not upgrade/use it for MacOS Sierra.

It would be good to add the OSX requirement  in the README  as a heads up.
 
   Cheers

**Comment by pakalvoltan** [comment]
Disregard my comment, I see it is described in the requirements, that it needs Sierra

Cheers
