### ISSUE TITLE
Form markup

### ISSUE THREAD

**Issue by ScullWM** [murlokswarm/app#49]
Hi,

I've made a small app available here https://github.com/updemia/client-macos but I've some strange thing.

On app startup, the updemia.app is open by the os browser, showing all assets files. I've find how to avoid this, removing the <form> markup. But then, app crash at startup.

Any idea ?

**Comment by maxence-charriere** [comment]
``` <form action="#">```  is targeting something local which not exist, so webkit open a file picker to choose a target for the action.

use a simple button instead of a submit input.
