### ISSUE TITLE
input type file doesn't work on mac

### ISSUE THREAD

**Issue by rand99** [murlokswarm/app#54]
I tried adding it in your example app in the render func

<input type="file" id="bla2" name="bla2"  />

but it doesn't do anything

**Comment by maxence-charriere** [comment]
this is an issue that come from the wkwebview.

Here is an example of how tu use a file picker: https://github.com/murlokswarm/app/issues/40.
```go
	app.NewFilePicker(app.FilePicker{
		MultipleSelection: false,
		NoDir:             true,
		NoFile:            false,
		OnPick: func(filenames []string) {
			// handle files
		},
	})
```
Hope it helps.
