### ISSUE TITLE
How to clear the text field after onchange?

### ISSUE THREAD

**Issue by anarchyrucks** [murlokswarm/app#57]

**Comment by maxence-charriere** [comment]
Depends of your implementation.
You can set the input value with a component field and set it with an empty string at each call of on change.

Here is a modified hello example that could work:
```go
type Hello struct {
	Greeting string
        Input string
}

func (h *Hello) Render() string {
	return `
<div class="WindowLayout">    
    <div class="HelloBox">
        <h1>
            Hello,
            <span>{{if .Greeting}}{{html .Greeting}}{{else}}World{{end}}</span>
        </h1>
        <input type="text" placeholder="What is your name?" value="{{html .Input}}" onchange="OnInputChange" />
    </div>
</div>
    `
}

func (h *Hello) OnInputChange(arg app.ChangeArg) {
	h.Greeting = arg.Value
        h.Input = ""
	app.Render(h)
}
```

*Not able to try it now, the is a possibility it doesn't work and in this case it will be fixed.

**Comment by anarchyrucks** [comment]
I was trying the same thing for a while but it doesn't work. Can you tell me where I should look into to find what the problem is?

**Comment by maxence-charriere** [comment]
the problem come in javascript when sync properties.
The is a diff but in this case, when you type in the input, the dom is not updated. so when it doest a diff between "" and "", not difference so it skip.

There is a check of the attribute name (value) to be added here: https://github.com/murlokswarm/app/blob/master/js.go#L31

also this may not be enough because there is also the attribute diff in the markup package when doing a sync.

can you try this too ?
```go
type Hello struct {
	Greeting string
        Input string
}

func (h *Hello) Render() string {
	return `
<div class="WindowLayout">    
    <div class="HelloBox">
        <h1>
            Hello,
            <span>{{if .Greeting}}{{html .Greeting}}{{else}}World{{end}}</span>
        </h1>
        <input type="text" placeholder="What is your name?" value="{{html .Input}}" onchange="OnInputChange" onkeydown="Input" />
    </div>
</div>
    `
}

func (h *Hello) OnInputChange(arg app.ChangeArg) {
	h.Greeting = arg.Value
        h.Input = ""
	app.Render(h)
}
```

**Comment by maxence-charriere** [comment]
adding the ```onkeydown="Input"``` may trick the diff.

**Comment by anarchyrucks** [comment]
The diff is clever! 😄  That does not work either.

**Comment by maxence-charriere** [comment]
Sorry about this :(.
I put it on my Todo list.

**Comment by anarchyrucks** [comment]
It's okay. I will play around with other things.
Hope this will replace Electron. 😉

**Comment by maxence-charriere** [comment]
I don't know if it can replace electron, It's a pretty rich environment.
Currently working on a v2, let's see how far I can go with this ;)
