### ISSUE TITLE
Cross platform driver

### ISSUE THREAD

**Issue by JackMordaunt** [murlokswarm/app#59]
Have you looked at [Sciter](https://www.sciter.com)? It's a lightweight (<5MB) HTML/CSS engine with [Go bindings](https://github.com/sciter-sdk/go-sciter). 

If we create a driver for Sciter, then we wouldn't need to create drivers for OSX, Windows and Linux. At least, not right away.

**Comment by maxence-charriere** [comment]
I wonder on what engine it is based.
That looks interesting.

The reason I want to use a WKWebview on Mac or the UWP web view widget on Windows are for theses reason:
- they are not embedded into the exec, they are part of the api.
- They are optimized to work on their native platform which imply better battery consumption.
These are things that are criticized  with Electron which use Chromium Embedded Framework.

Also it allows more flexibility for platform specific features implementations.

Also I'm not targeting only win/mac/linux. I'm working on a v2 that make platform specific stuff easier to deal with. I Have the ambition to use this framework to build IOS, Android and websites.

**Comment by JackMordaunt** [comment]
I agree with your reasoning. I think Sciter could be a good middle ground for those that want to use this framework on linux and windows asap, until native drivers are implemented for the respective OS's.

I'd be interested in building a prototype Sciter driver, but I don't know what's involved. What should I look at to learn how to build a driver?

**Comment by maxence-charriere** [comment]
Totally agree, I'm open to give a shot to this.
I just lack time to do all ^^. This weekend I gonna start the reimplementation od the Mac Driver with the new api.
My first goal is to have feature parity with v1.

**Comment by AnthoniG** [comment]
Do you have any time frames for when the Windows driver will be created ?
Also will the windows driver work on Win7 ?

**Comment by maxence-charriere** [comment]
I have no frame, currently implementing the mac driver with the new API.
The windows driver will be based on the Windows 10 API.

**Comment by joeblew99** [comment]
Hey all,
Been following this project for a while..
Some one has written a webview that works on windows, osx and linux.
Its very light and in c. Not like the heaviness of elecron.
it might be a good option for this project.

https://github.com/zserge/webview

**Comment by joeblew99** [comment]
the final exe on OSX is 10 MB. With electron its like 250 MB i think.

Here is a Makefile to run it easily.

````

# ref: https://github.com/zserge/webview


DIR=${PWD}

LIB_GO_PATH=github.com/zserge/webview
LIB_FILE_PATH=${GOPATH}/src/${LIB_GO_PATH}

EX_GO_PATH=${LIB_GO_PATH}/examples
EX_FILE_PATH=${GOPATH}/src/${EX_GO_PATH}



check:

	@echo "## Checking paths ##"
	@echo 

	@echo "DIR \t \t ${DIR}"
	@echo 

	@echo "LIB_GO_PATH: \t ${LIB_GO_PATH}"
	@echo "LIB_FILE_PATH: \t ${LIB_FILE_PATH}"
	@echo 

	@echo "EX_GO_PATH: \t ${EX_GO_PATH}"
	@echo "EX_FILE_PATH: \t ${EX_FILE_PATH}"
	@echo 



dep:

	go get -u ${LIB_GO_PATH}/...
	


dep-clean:

	# delete lib code
	rm -rf ${LIB_FILE_PATH}


open-bash:

	# open bash terminal
	open -a Terminal.app ${LIB_FILE_PATH}

open-fs:

	# Opens Finder.
	open ${LIB_FILE_PATH}

open-vsc:

	# Opens Visual Studio Code
	code ${LIB_FILE_PATH}

open-vs:

	# Opens Visual Studio for Mac
	open ${LIB_FILE_PATH}

	# Works and runs :)


run:

	cd ${EX_FILE_PATH}/minimal-go && go run main.go

build:

	#cd ${EX_FILE_PATH}/minimal-go && GOOS=windows GOARCH=amd64 go build -ldflags "-H=windowsgui" main.go
	cd ${EX_FILE_PATH}/minimal-go && go build .
	cd ${EX_FILE_PATH}/minimal-go && open ./minimal-go



run-active:

	cd ${LIB_FILE_PATH}/go-example && go run main.go

build-active:

	cd ${LIB_FILE_PATH}/go-example && go build .
	cd ${LIB_FILE_PATH}/go-example && open ./go-example





````

**Comment by joeblew99** [comment]
BTW i got golang webview working on android and IOS using xamarin and visual Studio for MAC.
It also has a c# to JS bridge, but you can call up from yur goang code into the JS and then out to the c#- The reason you want this is because at the c# level you get all this access to fire notifications, and all the other native things. Its very easy.

Will post when its done...

**Comment by nadilas** [comment]
@joeblew99 Sounds interesting, how far did you get?

**Comment by maxence-charriere** [comment]
Not planning to implement this myself.
If someone feels motivated, would be awesome.
Closing this now.
Reopen if required.
