### ISSUE TITLE
Commonly used selectors 

### ISSUE THREAD

**Issue by JennyZmx** [murlokswarm/app#79]
Where can I find commonly used selectors? The URL link in this page https://github.com/murlokswarm/app/wiki/Menu-Bar#selector
will direct you to the homepage of wiki, which has no information about selector. 

And, is there a function that can terminate the app? I want the app to terminate once I close the window.

**Comment by maxence-charriere** [comment]
Common macos selectors are at the bottom of the page.

Sent from my iPhone

On Nov 28, 2017, at 6:23 PM, JennyZmx <notifications@github.com<mailto:notifications@github.com>> wrote:


Where can I find commonly used selectors? The URL link in this page https://github.com/murlokswarm/app/wiki/Menu-Bar#selector
will direct you to the homepage of wiki, which has no information about selector.

And, is there a function that can terminate the app? I want the app to terminate once I close the window.
