### ISSUE TITLE
Handle keyboard event

### ISSUE THREAD

**Issue by JennyZmx** [murlokswarm/app#80]
I have a component whose content is supposed to change upon a event. 
`<div class = "MainScore MainCurrentScore" onclick = "UpdateScore">{{ .Current}}</div>`
The following is the function: 
`func (s *Score) UpdateScore() {`
        `s.Current = 5`
	`app.Render(s)`
`}`
I'm sure the rest of the go file works since the component actually can change upon mouse click. But if I change the element to 
`<div class = "MainScore MainCurrentScore" onkeydown = "UpdateScore">{{ .Current}}</div>`
the component won't change upon keyboard press. 
How to handle a keyboard event?

**Comment by maxence-charriere** [comment]
I think it is because a div does not propagate the onkeydown event that is defined in the html.
Try to put the onkeydown event on your input tag.

**Comment by JennyZmx** [comment]
But this is not an input box, it is actually a output box. As I tried, a lot of tags(including p, object,  button) do not work. Do you have other tags to suggest?

**Comment by maxence-charriere** [comment]
what are you trying to achieve with that keypress ? I mean in what scenario a user would press a key to update the score ?

**Comment by JennyZmx** [comment]
I'm building a simple game 2048, in which the player play game by pressing direction keys. After each move, the score and the board need to be updated.

**Comment by maxence-charriere** [comment]
I see, then maybe you should plug the key press to the menubar shortcut. an trigger it in the code.
Also try this little hack: https://stackoverflow.com/questions/3759339/keypress-on-a-div-tag

**Comment by JennyZmx** [comment]
Thank you for the suggestion! I finally fixed this by changing it into a button and added a property `autofocus="autofocus"`
