### ISSUE TITLE
Change class upon event

### ISSUE THREAD

**Issue by JennyZmx** [murlokswarm/app#81]
If it's possible to change a class of a div upon event? 
`<div class = "cell cell11 {{html .Cell11Class}}">2</div>
As I tried this does not work.

**Comment by JennyZmx** [comment]
`<div class = "cell cell11 {{html .Cell2Class}}">{{ .Cell2}}</div>`

**Comment by JennyZmx** [comment]
This div is inside a big component whose field will change upon keyboard event. As I just tried, an weird phenomenon is that if I press a key for one time, the class wouldn't be changed; while when I press a second time the class was changed  successfully...
The following is the function I used:
`func (g *Game2048) UpdateScore() {`
	`g.Cell2Class = "cell_4"`
	`app.Render(g)`
`}`

**Comment by maxence-charriere** [comment]
It should work, what is the value of the new class? Did you called render ?

Sent from my iPhone

On Nov 29, 2017, at 8:13 PM, JennyZmx <notifications@github.com<mailto:notifications@github.com>> wrote:


<div class = "cell cell11 {{html .Cell2Class}}">{{ .Cell2}}</div>

**Comment by JennyZmx** [comment]
`func (g *Game2048) UpdateScore() {`
`g.Cell2Class = "cell_4"`
`app.Render(g)`
`}`
This is the function I called.

**Comment by maxence-charriere** [comment]
what key event do you use ?

**Comment by JennyZmx** [comment]
I just used button with mouse click event, without using key board event like before.

**Comment by JennyZmx** [comment]
I found that if I don't change the content inside tags(i. e. set content to a constant number), the class can be changed properly. There seems to be some kind of delay in changing class if both class and content inside need to be changed.

**Comment by maxence-charriere** [comment]
The class value is updated only if it change. This is a normal behavior.

**Comment by JennyZmx** [comment]
What I tried to say is that sometimes (very frequently) I changed the class by updating a field but the change is not displayed properly.

**Comment by maxence-charriere** [comment]
is the content Is a text in the div ?

**Comment by JennyZmx** [comment]
Yes. I'm sorry for the misunderstanding.

**Comment by maxence-charriere** [comment]
try decorate the text with another tag like a ```span```

**Comment by JennyZmx** [comment]
That works really good!!! Thank you so much for that !!!

**Comment by maxence-charriere** [comment]
The problem is if you update a text directly, the whole node is replaced, skipping some css animations.
With this only the span is replaced and the class in the parent node is just updated.
