### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by XWCHAO** [murlokswarm/app#82]
Hi,

I try to test the Hello example by myself:
![image](https://user-images.githubusercontent.com/19710582/33464323-aa921c50-d60f-11e7-8d9f-f7e13e325bae.png)

And in the main() function, I add

`win.Mount(&Hello{})`

When I finish building and run it, I got this error below and the app exit automatically when clicking the text box. I also got the same error when testing the menu example in the /examples folder. Could you please help me find our the reason? Thanks!

![image](https://user-images.githubusercontent.com/19710582/33464158-f71111d6-d60e-11e7-902d-c8c57e0006f0.png)

**Comment by maxence-charriere** [comment]
Is the mac package is on its last version? It look like an issue i already close.

Sent from my iPhone

On Nov 30, 2017, at 5:48 PM, Xiwen Zhao <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I try to test the Hello example by myself:
[image]<https://user-images.githubusercontent.com/19710582/33464323-aa921c50-d60f-11e7-8d9f-f7e13e325bae.png>

And in the main() function, I add

win.Mount(&Hello{})

When I finish building and run it, I got this error below and the app exit automatically when clicking the text box. I also got the same error when testing the menu example in the /examples folder. Could you please help me find our the reason? Thanks!

[image]<https://user-images.githubusercontent.com/19710582/33464158-f71111d6-d60e-11e7-902d-c8c57e0006f0.png>

**Comment by XWCHAO** [comment]
Yes. I think I just clone this package several days ago.

**Comment by maxence-charriere** [comment]
Ok i ll take a look this weekend. Thanks for reporting this.

Sent from my iPhone

On Dec 1, 2017, at 9:32 AM, Xiwen Zhao <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes. I think I just clone this package several days ago.

**Comment by XWCHAO** [comment]
Actually my friend doesn't meet this problem when testing the examples. So maybe I did something wrong?

I have the Xcode of Version 9.1 (9B55), and go version go1.9 darwin/amd64.

I also test with a simple
`<input type="text" value="hello world" />`
, and still have the same problem when clicking the text box.

**Comment by maxence-charriere** [comment]
Can you try to build with ```go build -ldflags -s```.

**Comment by XWCHAO** [comment]
Same problem :(

**Comment by maxence-charriere** [comment]
What MacOS Version have you.
Can you try wi latest go version ?
Can you copy your main in the comment ?

**Comment by XWCHAO** [comment]
MacOS Sierra 10.12.6 (16G29)

I updated my go to the version 1.9.2, and also restart my computer. Got the same problem.

My main.go:

**Comment by XWCHAO** [comment]
```
package main

import "github.com/murlokswarm/app"

var (
	win app.Windower
)

func main() {
	app.OnLaunch = func() {
		if menuBar, ok := app.MenuBar(); ok {
			menuBar.Mount(&MenuBar{})
		}

		if dock, ok := app.Dock(); ok {
			dock.Mount(&DockMenu{})
		}

		win = newMainWindow()
		win.Mount(&Gobang{})
	}

	app.OnReopen = func() {
		if win != nil {
			return
		}
		win = newMainWindow()
		win.Mount(&Gobang{})
	}

	app.Run()
}

func newMainWindow() app.Windower {
	return app.NewWindow(app.Window{
		Title:           "nav",
		TitlebarHidden:  true,
		Width:           1280,
		Height:          768,
		BackgroundColor: "#FFFFFF",
		Vibrancy: 			 app.VibeDark,
		OnClose: func() bool {
			win = nil
			return true
		},
	})
}

```

**Comment by XWCHAO** [comment]
The Gobang is the component I have in another go file.

**Comment by XWCHAO** [comment]
hello.go:
```
package main

import "github.com/murlokswarm/app"

type Hello struct {
  Name string
}

func(h *Hello) Render() string {
  return `
<div>
  <h1>
    Hello,
    <span>{{html .Name}}</span>
  </h1>
  <input type="text" onchange="OnInputChange" />
</div>
  `
}

func (h *Hello) OnInputChange(a app.ChangeArg) {
  h.Name = a.Value
  app.Render(h)
}

type World struct {
  Name string
}

func (w *World) Render() string {
  return `
<span>
  {{if .Name}}
    {{html .Name}}
  {{else}}
    World
  {{end}}
</span>
  `
}

func init() {
  app.RegisterComponent(&Hello{})
  app.RegisterComponent(&World{})
}

```

**Comment by maxence-charriere** [comment]
Can you copy your main in the comment, the full main?

**Comment by maxence-charriere** [comment]
Did you modify something from the example ?

**Comment by XWCHAO** [comment]
I downloaded the whole "app" folder again, opened the examples/menu, then `go build; ./menu`. The window shows up, and when I click the text box, it just exit with the error shown in terminal:
```
Sharons-MacBook-Pro:menu xiwenz$ ./menu
INFO  2017/12/02 09:00:26 driver.go:57: driver *mac.Driver is loaded
INFO  2017/12/02 09:00:26 component.go:62: main.CustomMenu has been registered under the tag CustomMenu
INFO  2017/12/02 09:00:26 component.go:62: main.EditMenu has been registered under the tag EditMenu
INFO  2017/12/02 09:00:26 component.go:62: main.Home has been registered under the tag Home
INFO  2017/12/02 09:00:26 component.go:62: main.MenuBar has been registered under the tag MenuBar
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fff9a37fb52]

runtime stack:
runtime.throw(0x4207fc0, 0x2a)
	/usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:351 +0x2b8

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4190fb0, 0xc420055f38, 0x4006774)
	/usr/local/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc420055f08 sp=0xc420055ec8 pc=0x4003a34
github.com/murlokswarm/mac._Cfunc_Driver_Run()
	github.com/murlokswarm/mac/_obj/_cgo_gotypes.go:157 +0x41 fp=0xc420055f38 sp=0xc420055f08 pc=0x4184b91
github.com/murlokswarm/mac.(*Driver).Run(0xc42007eb10)
	/Users/zxw/go/src/github.com/murlokswarm/mac/driver.go:54 +0x29 fp=0xc420055f48 sp=0xc420055f38 pc=0x41874e9
github.com/murlokswarm/app.Run()
	/Users/zxw/go/src/github.com/murlokswarm/app/app.go:49 +0x35 fp=0xc420055f60 sp=0xc420055f48 pc=0x417b8e5
main.main()
	/Users/zxw/Desktop/app-master/examples/menu/main.go:27 +0x48 fp=0xc420055f80 sp=0xc420055f60 pc=0x41902d8
runtime.main()
	/usr/local/go/src/runtime/proc.go:195 +0x226 fp=0xc420055fe0 sp=0xc420055f80 pc=0x402d336
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420055fe8 sp=0xc420055fe0 pc=0x40583e1

goroutine 5 [chan receive]:
github.com/murlokswarm/app.startUIGoroutine()
	/Users/zxw/go/src/github.com/murlokswarm/app/ui.go:109 +0x5f
created by github.com/murlokswarm/app.init.0
	/Users/zxw/go/src/github.com/murlokswarm/app/ui.go:103 +0xa0
```

So basically I didn't change anything from your code. I just downloaded it, and built. :(

**Comment by CunTianXing** [comment]
I also encountered the same problem

**Comment by CunTianXing** [comment]
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fff95fe1b52]

runtime stack:
runtime.throw(0x420a467, 0x2a)
	/data/golang/go/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
	/data/golang/go/src/runtime/signal_unix.go:351 +0x2b8

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x41933c0, 0xc42004df38, 0x4007254)
	/data/golang/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc42004df08 sp=0xc42004dec8 pc=0x4004514
github.com/murlokswarm/mac._Cfunc_Driver_Run()
	github.com/murlokswarm/mac/_obj/_cgo_gotypes.go:157 +0x41 fp=0xc42004df38 sp=0xc42004df08 pc=0x4187601
github.com/murlokswarm/mac.(*Driver).Run(0xc42007cae0)
	/data/go/src/github.com/murlokswarm/mac/driver.go:54 +0x29 fp=0xc42004df48 sp=0xc42004df38 pc=0x4189f59
github.com/murlokswarm/app.Run()
	/data/go/src/github.com/murlokswarm/app/app.go:49 +0x35 fp=0xc42004df60 sp=0xc42004df48 pc=0x417dd95
main.main()
	/data/go/src/github.com/CunTianXing/test/demo22.go:48 +0x3a fp=0xc42004df80 sp=0xc42004df60 pc=0x41929da
runtime.main()
	/data/golang/go/src/runtime/proc.go:195 +0x226 fp=0xc42004dfe0 sp=0xc42004df80 pc=0x402de16
runtime.goexit()
	/data/golang/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42004dfe8 sp=0xc42004dfe0 pc=0x4058ec1

goroutine 19 [chan receive]:
github.com/murlokswarm/app.startUIGoroutine()
	/data/go/src/github.com/murlokswarm/app/ui.go:109 +0x5f
created by github.com/murlokswarm/app.init.0
	/data/go/src/github.com/murlokswarm/app/ui.go:103 +0xa0
exit status 2

**Comment by maxence-charriere** [comment]
can you try to use this:
```xcode-select --install```
I go some weird issue recently even with my Xcode up to date.
Using that solved my crashes.

**Comment by maxence-charriere** [comment]
Reopen if this is still here
