### ISSUE TITLE
How to get a component as a composition

### ISSUE THREAD

**Issue by JennyZmx** [murlokswarm/app#83]
I have a big component with several compositions. As these small components are declared inside, how can I get one of them and modify the field as I want? 
As I noticed, only one component can be mounted onto a window right? I tried to mount multiple components and only one of they showed up.

**Comment by maxence-charriere** [comment]
You can't, component are self are handling their own fields.
If you want to modify field from a subcomponent, you should change the component properties in you parent render function.

If you want to make component communicate with each other, I recommend to use a messenger or full design pattern.

**Comment by JennyZmx** [comment]
What do you mean by a messenger?

**Comment by maxence-charriere** [comment]
sorry a mediator => https://en.wikipedia.org/wiki/Mediator_pattern

**Comment by JennyZmx** [comment]
I'll try flux, thanks!
