### ISSUE TITLE
Same program with different performance in different directory

### ISSUE THREAD

**Issue by JennyZmx** [murlokswarm/app#85]
I'm working on MacOS High Sierra (10.13.1). Both two folders lie within $GOPATH/src, and $GOPATH is under my home directory. I write the code in one folder first and it runs perfectly normal (go build then ./foldername). Then I created a new folder in $GOPATH/src with different name. I copied all files in the original folder by control+c and pasted it into the new folder by control+v. The new folder can build but the window won't show up. Does you have any clue why this may happen? 

This is the information in command line if I try to run the new folder:
`Mengxins-MBP:tt zhangmengxin$ ./tt`
`INFO  2017/12/01 18:00:41 driver.go:57: driver *mac.Driver is loaded`
`INFO  2017/12/01 18:00:41 component.go:62: main.Game2048 has been registered under the tag`
`Game2048`

This is the information in command line if I try to run the old folder:
`Mengxins-MBP:test zhangmengxin$ ./test`
`INFO  2017/12/01 18:04:59 driver.go:57: driver *mac.Driver is loaded`
`INFO  2017/12/01 18:04:59 component.go:62: main.Game2048 has been registered under the tag` `Game2048`

**UPDATE:** It turns out that I don't even need to move the file... The program performs differently even if I just change the folder name.

**Comment by maxence-charriere** [comment]
Mmm that's strange, I tried it on MacOS High Sierra (10.13.1) but was unable to reproduce that behavior.

**Comment by JennyZmx** [comment]
That's wired...My friend also can build the folder pretty normally after changing folder names... I re-installed Go and that's still the case. For now, I'll just keep the folder name anyway. Thanks!

**Comment by JennyZmx** [comment]
Actually the dock will show at the bottom. If I select "show all window", there will be a thick blue border showing up. It looks like the window is there and it is just invisible...
