### ISSUE TITLE
Show a second window

### ISSUE THREAD

**Issue by JennyZmx** [murlokswarm/app#87]
I implemented a second window as the following function. The following function will be called, and supposedly a window will show, when I clicked a menu item in menu bar. ScoreBoard is a component that has already been declared as global variable. When I click menu item, no window showed up. If I click a second up, an error will show as following: 

![1512240119312](https://user-images.githubusercontent.com/33711433/33518657-a13ec24a-d766-11e7-9476-c5e5a49e079f.jpg)

This is the function: 
`func (m *MainMenu) OpenScoreBoard() {`
  `ScoreWindow = app.NewWindow(app.Window{`
    `Title:          "Score Board",`
    `MinWidth:        497,`
    `MinHeight:       405,`
   ` MaxWidth:        497,`
   ` MaxHeight:       405,`
    `BackgroundColor: "#EDC22F",`
	`})`
    `ScoreWindow.Mount(ScoreBoard)`
`}`

Is there anything else I need to do in order to show a second window?

**Comment by maxence-charriere** [comment]
your ScoreRecord should not be mounted in two different window. you should mount a new instance of of ScoreRecord in the new window.
