### ISSUE TITLE
Arithmetic in Go templates

### ISSUE THREAD

**Issue by XWCHAO** [murlokswarm/app#88]
Hi,

I'd like to do some simple arithmetic calculations in html template. For example, {{.X}}+1. I googled about this and most people believe a new template function should be written and called whenever need to calculate. Here's a example link:

https://stackoverflow.com/questions/25689829/arithmetic-in-go-templates

However, since your code have this "Parse" process in the back. I don't know where to define a function like this. Could you please help me out?

**Comment by maxence-charriere** [comment]
The package use just the template syntaxe for generating html. Because it handle all the logic to translate component to html, you can't do all the feature that the standard template package do.

A solution for that would be to implement the TemplateFuncMapper interface => https://github.com/murlokswarm/app/blob/master/component.go#L39

you could do something like:
```go
func (c *YourComponent) FuncMaps() template.FuncMap {
	return template.FuncMap{
		"add": func(x, y int) int {
			return x + y
		},
	}
}

func (c *YourComponent) Render() string {
	return `
<div>
	x + 1 = {{add .X 1}}
</div>
	`
}
```

But honestly, I think your html should just contain your interface description. This kind of operation should be done in go code.

**Comment by XWCHAO** [comment]
I tested your suggestions.
In the returned html string of Render(), I have the following code.
```
{{range $i, $row := .Board}}
      	{{range $j, $elem := $row}}
      		{{if eq $elem 1}}
      			<circle cx="{{add 15 $i}}" cy="{{add 15 $j}}" r="12" fill="url(#grad)" />
      		{{else if eq $elem 2}}
      			<circle cx="{add 15 $i}}" cy="{{add 15 $j}}" r="12" fill="white" />
      		{{end}}
      	{{end}}
      {{end}}
```
And in the go part, I added the following function:
```
func (g *Gobang) FuncMaps() template.FuncMap {
	return template.FuncMap{
		"add": func(x, y int) int {
			return x + y
		},
	}
}
```
I can build it. But when I run it, I got the error:
`panic: template: Render:65: function "add" not defined
`
How could that be?

**Comment by maxence-charriere** [comment]
Is it template/text or template/html that is imported ?

Sent from my iPhone

On Dec 2, 2017, at 1:47 PM, Xiwen Zhao <notifications@github.com<mailto:notifications@github.com>> wrote:


I tested your suggestions.
In the returned html string of Render(), I have the following code.

{{range $i, $row := .Board}}
        {{range $j, $elem := $row}}
                {{if eq $elem 1}}
                        <circle cx="{{add 15 $i}}" cy="{{add 15 $j}}" r="12" fill="url(#grad)" />
                {{else if eq $elem 2}}
                        <circle cx="{add 15 $i}}" cy="{{add 15 $j}}" r="12" fill="white" />
                {{end}}
        {{end}}
      {{end}}


And in the go part, I added the following function:

func (g *Gobang) FuncMaps() template.FuncMap {
        return template.FuncMap{
                "add": func(x, y int) int {
                        return x + y
                },
        }
}


I can build it. But when I run it, I got the error:
panic: template: Render:65: function "add" not defined
How could that be?

**Comment by XWCHAO** [comment]
Yes. I used html/template before. Now I changed to text/html, and "add" can be done normally. 

However, when I want to do nested calculations, e.g. 15 + 30 * {{.X}}, the code below doesn't work.
In html:
`{{add 15 {{multi 30 $i}}}}`
In go:
```
func (g *Gobang) FuncMaps() template.FuncMap {
	return template.FuncMap{
		"add": func(x, y int) int {
			return x + y
		},
    "multi": func(x, y int) int {
			return x * y
		},
	}
}
```
The error is:
`panic: template: Render:68: unexpected "{" in operand
`

So what should I do if I want to do add and multiply at the same time?

**Comment by maxence-charriere** [comment]
did you tried, ```{{add 15 multi 30 $i}}```?
Also I dont know if go template accept ```$i```.

This is a problem related to go standard template library.
Would be better to send me private messages or ask directly to go template dedicated resources.

**Comment by XWCHAO** [comment]
I got the error:
`ERROR 2017/12/02 23:48:45 app.go:57: unable to render *main.Gobang: template: Render:68:23: executing "Render" at <add>: wrong number of args for add: want 2 got 4`
So I think it doesn't work.

I tested with {{add 15 $i}} and {{multi 15 $i}}, they work. So I think go template can accept $i.

**Comment by maxence-charriere** [comment]
```{{add 15 (multi 30 $i)}}```
=> https://golang.org/pkg/text/template/#hdr-Examples

**Comment by XWCHAO** [comment]
Thanks!!!!! I fixed it.

Have a good day! :)
