### ISSUE TITLE
Example application

### ISSUE THREAD

**Issue by grocid** [murlokswarm/app#97]
Here is an application I wrote using murlokswarm (loosely based on the example): https://github.com/grocid/PassMacOS

It may not be the best way to implement stuff, so maybe it is not a good example of how people *should* do. However, it works fine.

**Comment by maxence-charriere** [comment]
Whoa, that is super cool 👍 .
Hope the experience building it was good.
Gonna put a link to the other example.
Thanks a lot for showing me this!

**Comment by grocid** [comment]
By the way... I might have found a bug.

```
<textarea  placeholder="Username" autocomplete="off">{{.Username}}</textarea>
```

seems to get formatted internally, is that correct. This causes the textarea to contain indentation, i.e., unwanted spaces.
