### ISSUE TITLE
Getting value when contenteditable is true

### ISSUE THREAD

**Issue by neonima** [murlokswarm/app#99]
For example `<h1 contenteditable="true" onchange="Edited>smth</h1>`, so that we don't need to change the style of divs or texts block if we need to edit it

**Comment by maxence-charriere** [comment]
I don't think th on change event work with this. 
It is specific to tag like ```input```.
Usually, the onkey events are used for this.

The problem here is how to get the value when ant event is handled.
Gonna add this on my todo list.
Thanks for reporting that issue.

**Comment by maxence-charriere** [comment]
when ```contenteditable``` is set, can get its value from the event handler arg.

```go
type Event Struct {
    InnerText string
}

func (c *MyComponent) Render() string {
    return `<p contenteditable onkeyup="OnKeyUp">Edit me</p>`
}

func (c *MyComponent) OnKeyUp(e Event) {
    // Your code
}
```

You can also use a ```app.MouseEvent``` or ```app.KeyboardEvent``` as handler argument.
